// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: cormoran/fast_keymap/fast_keymap.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cormoran.fast_keymap";

export const ErrorCode = {
  ERR_GENERIC: 0,
  ERR_INVALID_LAYER: 1,
  ERR_INVALID_BEHAVIOR: 2,
  ERR_INVALID_LAYOUT: 3,
  UNRECOGNIZED: -1,
} as const;

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];

export namespace ErrorCode {
  export type ERR_GENERIC = typeof ErrorCode.ERR_GENERIC;
  export type ERR_INVALID_LAYER = typeof ErrorCode.ERR_INVALID_LAYER;
  export type ERR_INVALID_BEHAVIOR = typeof ErrorCode.ERR_INVALID_BEHAVIOR;
  export type ERR_INVALID_LAYOUT = typeof ErrorCode.ERR_INVALID_LAYOUT;
  export type UNRECOGNIZED = typeof ErrorCode.UNRECOGNIZED;
}

/**
 * enum BehaviorDetailsMode -- see DESIGN.md SS5 for the semantics of each
 * mode.
 */
export const BehaviorDetailsMode = {
  /** BEHAVIOR_DETAILS_NONE - slim summaries only */
  BEHAVIOR_DETAILS_NONE: 0,
  /** BEHAVIOR_DETAILS_CUSTOM - inline details for non-standard behaviors */
  BEHAVIOR_DETAILS_CUSTOM: 1,
  /** BEHAVIOR_DETAILS_ALL - inline details for every behavior */
  BEHAVIOR_DETAILS_ALL: 2,
  UNRECOGNIZED: -1,
} as const;

export type BehaviorDetailsMode = typeof BehaviorDetailsMode[keyof typeof BehaviorDetailsMode];

export namespace BehaviorDetailsMode {
  export type BEHAVIOR_DETAILS_NONE = typeof BehaviorDetailsMode.BEHAVIOR_DETAILS_NONE;
  export type BEHAVIOR_DETAILS_CUSTOM = typeof BehaviorDetailsMode.BEHAVIOR_DETAILS_CUSTOM;
  export type BEHAVIOR_DETAILS_ALL = typeof BehaviorDetailsMode.BEHAVIOR_DETAILS_ALL;
  export type UNRECOGNIZED = typeof BehaviorDetailsMode.UNRECOGNIZED;
}

/** enum LayoutDetailsMode -- see DESIGN.md SS6 for the semantics of each mode. */
export const LayoutDetailsMode = {
  /** LAYOUT_DETAILS_NONE - slim summaries only (no geometry) */
  LAYOUT_DETAILS_NONE: 0,
  /** LAYOUT_DETAILS_ALL - inline every layout's geometry */
  LAYOUT_DETAILS_ALL: 1,
  UNRECOGNIZED: -1,
} as const;

export type LayoutDetailsMode = typeof LayoutDetailsMode[keyof typeof LayoutDetailsMode];

export namespace LayoutDetailsMode {
  export type LAYOUT_DETAILS_NONE = typeof LayoutDetailsMode.LAYOUT_DETAILS_NONE;
  export type LAYOUT_DETAILS_ALL = typeof LayoutDetailsMode.LAYOUT_DETAILS_ALL;
  export type UNRECOGNIZED = typeof LayoutDetailsMode.UNRECOGNIZED;
}

export interface Request {
  getSnapshot?: boolean | undefined;
  listBehaviors?:
    | ListBehaviorsRequest
    | undefined;
  /** batch details (miss-repair) */
  getBehaviors?:
    | GetBehaviorsRequest
    | undefined;
  /** current/effective */
  getLayer?:
    | GetLayerRequest
    | undefined;
  /** DT stock default */
  getDefaultLayer?:
    | GetLayerRequest
    | undefined;
  /** diff current vs default */
  getEditedLayer?:
    | GetLayerRequest
    | undefined;
  /** slim summary (+ optional geometry) */
  getPhysicalLayouts?:
    | GetPhysicalLayoutsRequest
    | undefined;
  /** one layout's geometry */
  getPhysicalLayout?:
    | GetPhysicalLayoutRequest
    | undefined;
  /** batch current/effective (cold load) */
  getLayers?: GetLayersRequest | undefined;
}

export interface Response {
  error?: ErrorResponse | undefined;
  snapshot?: Snapshot | undefined;
  listBehaviors?: ListBehaviorsResponse | undefined;
  getBehaviors?: GetBehaviorsResponse | undefined;
  getLayer?: Layer | undefined;
  getDefaultLayer?: Layer | undefined;
  getEditedLayer?: EditedLayer | undefined;
  getPhysicalLayouts?: PhysicalLayoutsResponse | undefined;
  getPhysicalLayout?: PhysicalLayoutResponse | undefined;
  getLayers?: GetLayersResponse | undefined;
}

export interface GetLayerRequest {
  layerId: number;
}

/**
 * Batch fetch of several layers' current/effective bindings in one round-trip
 * (DESIGN.md SS7). On a cold load a client wants every layer at once, and one
 * get_layer per layer is more round-trips than the whole keymap needs -- this
 * collapses them. Unknown/invalid ids are skipped (like get_behaviors), not an
 * error. `layer_ids` is bounded (max_count:32, fits the RX buffer); chunk more.
 */
export interface GetLayersRequest {
  layerIds: number[];
}

export interface GetLayersResponse {
  layers: Layer[];
}

export interface ErrorResponse {
  code: ErrorCode;
}

/**
 * Cheap cache keys for every data group this subsystem serves, so a client
 * with a warm cache can skip re-fetching groups whose fingerprint matches.
 * See DESIGN.md SS4 for the exact canonicalization each fingerprint hashes.
 */
export interface Snapshot {
  definitionVersion: number;
  behaviorsFp: number;
  defaultKeymapFp: number;
  keymapFp: number;
  physicalLayoutFp: number;
  behaviorCount: number;
  maxLayerNameLength: number;
  availableLayers: number;
  activeLayoutIndex: number;
  layers: LayerFingerprint[];
  /**
   * Width (bits) def_fp is served at on this device: the smallest of 16/24/32
   * at which every behavior's def_fp stays distinct (SS4). The web masks its
   * bundle/cache def_fp keys to this width. 0 is treated as 16 for backward
   * compatibility.
   */
  defFpBits: number;
}

export interface LayerFingerprint {
  id: number;
  name: string;
  bindingCount: number;
  fp: number;
  defaultFp: number;
  editedCount: number;
}

export interface ListBehaviorsRequest {
  details: BehaviorDetailsMode;
  /**
   * Include BehaviorDetails.alias in any inlined details. Off by default:
   * the alias is only needed to render/export a behavior's `&<alias>` token,
   * and for standard behaviors the client already has it from its bundle
   * (def_fp still hashes the true alias either way, SS4/SS5). A client that
   * doesn't render aliases leaves this false to save those bytes.
   */
  includeAlias: boolean;
  /**
   * BehaviorDetails.display_name is included by default (opt-out): set this
   * to omit it when the client doesn't render a behavior's human name. As
   * with alias, def_fp still hashes the true display_name regardless.
   */
  excludeDisplayName: boolean;
}

export interface ListBehaviorsResponse {
  behaviors: BehaviorSummary[];
}

/**
 * Slim: on the wire this is normally just local_id + def_fp (~7-8 B; def_fp
 * is truncated to 16 bits -- see SS4/docs/protocol.md); `details` is present
 * only per the request's BehaviorDetailsMode (SS5).
 */
export interface BehaviorSummary {
  localId: number;
  /** content-addressed identity + validator (low 16 bits), see SS4 */
  defFp: number;
  details: BehaviorDetails | undefined;
}

/**
 * The official details tree (zmk.behaviors.GetBehaviorDetailsResponse)
 * factored into a reusable submessage. Carries NO fingerprint (the client uses
 * BehaviorSummary.def_fp, SS4/SS5). `display_name` is present by default and
 * `alias` only when requested (see ListBehaviorsRequest.include_alias /
 * exclude_display_name); an omitted field is proto3's default "". def_fp still
 * hashes the true alias + display_name regardless of what is served here.
 */
export interface BehaviorDetails {
  displayName: string;
  alias: string;
  metadata: BehaviorBindingParametersSet[];
}

/**
 * Miss-repair batch fetch (SS5): resolve exactly the behaviors the client
 * couldn't resolve from its bundle/cache, in one round-trip.
 */
export interface GetBehaviorsRequest {
  /** .options: max_count:32 (fits RX buf) */
  behaviorIds: number[];
  /** see ListBehaviorsRequest.include_alias */
  includeAlias: boolean;
  /** see ListBehaviorsRequest.exclude_display_name */
  excludeDisplayName: boolean;
}

export interface GetBehaviorsResponse {
  behaviors: BehaviorEntry[];
}

export interface BehaviorEntry {
  id: number;
  details: BehaviorDetails | undefined;
}

export interface BehaviorBindingParametersSet {
  param1: BehaviorParameterValueDescription[];
  param2: BehaviorParameterValueDescription[];
}

export interface BehaviorParameterValueDescriptionRange {
  min: number;
  max: number;
}

export interface BehaviorParameterNil {
}

export interface BehaviorParameterLayerId {
}

export interface BehaviorParameterHidUsage {
  keyboardMax: number;
  consumerMax: number;
}

export interface BehaviorParameterValueDescription {
  name: string;
  nil?: BehaviorParameterNil | undefined;
  constant?: number | undefined;
  range?: BehaviorParameterValueDescriptionRange | undefined;
  hidUsage?: BehaviorParameterHidUsage | undefined;
  layerId?: BehaviorParameterLayerId | undefined;
}

export interface BehaviorBinding {
  behaviorId: number;
  param1: number;
  param2: number;
}

export interface Layer {
  id: number;
  name: string;
  bindings: BehaviorBinding[];
}

export interface EditedBinding {
  position: number;
  binding: BehaviorBinding | undefined;
}

export interface EditedLayer {
  id: number;
  bindings: EditedBinding[];
}

export interface GetPhysicalLayoutsRequest {
  details: LayoutDetailsMode;
}

export interface GetPhysicalLayoutRequest {
  layoutIndex: number;
}

/**
 * Slim summary + on-demand geometry (DESIGN.md SS6): `keys` is populated only
 * in LAYOUT_DETAILS_ALL mode (get_physical_layouts) or a single-layout fetch
 * (get_physical_layout) -- omitted (empty) otherwise, so proto3 drops it for
 * free on the wire.
 */
export interface PhysicalLayoutsResponse {
  activeLayoutIndex: number;
  layouts: PhysicalLayoutSummary[];
}

export interface PhysicalLayoutResponse {
  index: number;
  /** keys always populated */
  layout: PhysicalLayoutSummary | undefined;
}

export interface PhysicalLayoutSummary {
  name: string;
  /** per-layout fingerprint, device-opaque (SS4/SS6) */
  fp: number;
  keys: KeyPhysicalAttrs[];
  /**
   * Almost every key on a board shares one width/height (e.g. 100x100), so
   * the firmware hoists the common size here and omits each key's
   * width/height when it matches -- a KeyPhysicalAttrs with width/height 0
   * means "use these defaults" (a real key is never 0-sized). Saves ~6 B
   * per key on a uniform board (SS6). Only populated alongside `keys`
   * (LAYOUT_DETAILS_ALL / get_physical_layout); the fp still hashes each
   * key's true width/height, so this is a pure wire encoding, not a data
   * change.
   */
  defaultWidth: number;
  defaultHeight: number;
}

export interface KeyPhysicalAttrs {
  width: number;
  height: number;
  x: number;
  y: number;
  r: number;
  rx: number;
  ry: number;
}

function createBaseRequest(): Request {
  return {
    getSnapshot: undefined,
    listBehaviors: undefined,
    getBehaviors: undefined,
    getLayer: undefined,
    getDefaultLayer: undefined,
    getEditedLayer: undefined,
    getPhysicalLayouts: undefined,
    getPhysicalLayout: undefined,
    getLayers: undefined,
  };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.getSnapshot !== undefined) {
      writer.uint32(8).bool(message.getSnapshot);
    }
    if (message.listBehaviors !== undefined) {
      ListBehaviorsRequest.encode(message.listBehaviors, writer.uint32(18).fork()).join();
    }
    if (message.getBehaviors !== undefined) {
      GetBehaviorsRequest.encode(message.getBehaviors, writer.uint32(26).fork()).join();
    }
    if (message.getLayer !== undefined) {
      GetLayerRequest.encode(message.getLayer, writer.uint32(34).fork()).join();
    }
    if (message.getDefaultLayer !== undefined) {
      GetLayerRequest.encode(message.getDefaultLayer, writer.uint32(42).fork()).join();
    }
    if (message.getEditedLayer !== undefined) {
      GetLayerRequest.encode(message.getEditedLayer, writer.uint32(50).fork()).join();
    }
    if (message.getPhysicalLayouts !== undefined) {
      GetPhysicalLayoutsRequest.encode(message.getPhysicalLayouts, writer.uint32(58).fork()).join();
    }
    if (message.getPhysicalLayout !== undefined) {
      GetPhysicalLayoutRequest.encode(message.getPhysicalLayout, writer.uint32(66).fork()).join();
    }
    if (message.getLayers !== undefined) {
      GetLayersRequest.encode(message.getLayers, writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.getSnapshot = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.listBehaviors = ListBehaviorsRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.getBehaviors = GetBehaviorsRequest.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.getLayer = GetLayerRequest.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.getDefaultLayer = GetLayerRequest.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.getEditedLayer = GetLayerRequest.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.getPhysicalLayouts = GetPhysicalLayoutsRequest.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.getPhysicalLayout = GetPhysicalLayoutRequest.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.getLayers = GetLayersRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Request>): Request {
    return Request.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Request>): Request {
    const message = createBaseRequest();
    message.getSnapshot = object.getSnapshot ?? undefined;
    message.listBehaviors = (object.listBehaviors !== undefined && object.listBehaviors !== null)
      ? ListBehaviorsRequest.fromPartial(object.listBehaviors)
      : undefined;
    message.getBehaviors = (object.getBehaviors !== undefined && object.getBehaviors !== null)
      ? GetBehaviorsRequest.fromPartial(object.getBehaviors)
      : undefined;
    message.getLayer = (object.getLayer !== undefined && object.getLayer !== null)
      ? GetLayerRequest.fromPartial(object.getLayer)
      : undefined;
    message.getDefaultLayer = (object.getDefaultLayer !== undefined && object.getDefaultLayer !== null)
      ? GetLayerRequest.fromPartial(object.getDefaultLayer)
      : undefined;
    message.getEditedLayer = (object.getEditedLayer !== undefined && object.getEditedLayer !== null)
      ? GetLayerRequest.fromPartial(object.getEditedLayer)
      : undefined;
    message.getPhysicalLayouts = (object.getPhysicalLayouts !== undefined && object.getPhysicalLayouts !== null)
      ? GetPhysicalLayoutsRequest.fromPartial(object.getPhysicalLayouts)
      : undefined;
    message.getPhysicalLayout = (object.getPhysicalLayout !== undefined && object.getPhysicalLayout !== null)
      ? GetPhysicalLayoutRequest.fromPartial(object.getPhysicalLayout)
      : undefined;
    message.getLayers = (object.getLayers !== undefined && object.getLayers !== null)
      ? GetLayersRequest.fromPartial(object.getLayers)
      : undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return {
    error: undefined,
    snapshot: undefined,
    listBehaviors: undefined,
    getBehaviors: undefined,
    getLayer: undefined,
    getDefaultLayer: undefined,
    getEditedLayer: undefined,
    getPhysicalLayouts: undefined,
    getPhysicalLayout: undefined,
    getLayers: undefined,
  };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(10).fork()).join();
    }
    if (message.snapshot !== undefined) {
      Snapshot.encode(message.snapshot, writer.uint32(18).fork()).join();
    }
    if (message.listBehaviors !== undefined) {
      ListBehaviorsResponse.encode(message.listBehaviors, writer.uint32(26).fork()).join();
    }
    if (message.getBehaviors !== undefined) {
      GetBehaviorsResponse.encode(message.getBehaviors, writer.uint32(34).fork()).join();
    }
    if (message.getLayer !== undefined) {
      Layer.encode(message.getLayer, writer.uint32(42).fork()).join();
    }
    if (message.getDefaultLayer !== undefined) {
      Layer.encode(message.getDefaultLayer, writer.uint32(50).fork()).join();
    }
    if (message.getEditedLayer !== undefined) {
      EditedLayer.encode(message.getEditedLayer, writer.uint32(58).fork()).join();
    }
    if (message.getPhysicalLayouts !== undefined) {
      PhysicalLayoutsResponse.encode(message.getPhysicalLayouts, writer.uint32(66).fork()).join();
    }
    if (message.getPhysicalLayout !== undefined) {
      PhysicalLayoutResponse.encode(message.getPhysicalLayout, writer.uint32(74).fork()).join();
    }
    if (message.getLayers !== undefined) {
      GetLayersResponse.encode(message.getLayers, writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.snapshot = Snapshot.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.listBehaviors = ListBehaviorsResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.getBehaviors = GetBehaviorsResponse.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.getLayer = Layer.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.getDefaultLayer = Layer.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.getEditedLayer = EditedLayer.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.getPhysicalLayouts = PhysicalLayoutsResponse.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.getPhysicalLayout = PhysicalLayoutResponse.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.getLayers = GetLayersResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Response>): Response {
    return Response.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Response>): Response {
    const message = createBaseResponse();
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    message.snapshot = (object.snapshot !== undefined && object.snapshot !== null)
      ? Snapshot.fromPartial(object.snapshot)
      : undefined;
    message.listBehaviors = (object.listBehaviors !== undefined && object.listBehaviors !== null)
      ? ListBehaviorsResponse.fromPartial(object.listBehaviors)
      : undefined;
    message.getBehaviors = (object.getBehaviors !== undefined && object.getBehaviors !== null)
      ? GetBehaviorsResponse.fromPartial(object.getBehaviors)
      : undefined;
    message.getLayer = (object.getLayer !== undefined && object.getLayer !== null)
      ? Layer.fromPartial(object.getLayer)
      : undefined;
    message.getDefaultLayer = (object.getDefaultLayer !== undefined && object.getDefaultLayer !== null)
      ? Layer.fromPartial(object.getDefaultLayer)
      : undefined;
    message.getEditedLayer = (object.getEditedLayer !== undefined && object.getEditedLayer !== null)
      ? EditedLayer.fromPartial(object.getEditedLayer)
      : undefined;
    message.getPhysicalLayouts = (object.getPhysicalLayouts !== undefined && object.getPhysicalLayouts !== null)
      ? PhysicalLayoutsResponse.fromPartial(object.getPhysicalLayouts)
      : undefined;
    message.getPhysicalLayout = (object.getPhysicalLayout !== undefined && object.getPhysicalLayout !== null)
      ? PhysicalLayoutResponse.fromPartial(object.getPhysicalLayout)
      : undefined;
    message.getLayers = (object.getLayers !== undefined && object.getLayers !== null)
      ? GetLayersResponse.fromPartial(object.getLayers)
      : undefined;
    return message;
  },
};

function createBaseGetLayerRequest(): GetLayerRequest {
  return { layerId: 0 };
}

export const GetLayerRequest: MessageFns<GetLayerRequest> = {
  encode(message: GetLayerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.layerId !== 0) {
      writer.uint32(8).uint32(message.layerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetLayerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetLayerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.layerId = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetLayerRequest>): GetLayerRequest {
    return GetLayerRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetLayerRequest>): GetLayerRequest {
    const message = createBaseGetLayerRequest();
    message.layerId = object.layerId ?? 0;
    return message;
  },
};

function createBaseGetLayersRequest(): GetLayersRequest {
  return { layerIds: [] };
}

export const GetLayersRequest: MessageFns<GetLayersRequest> = {
  encode(message: GetLayersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.layerIds) {
      writer.uint32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetLayersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetLayersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.layerIds.push(reader.uint32());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.layerIds.push(reader.uint32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetLayersRequest>): GetLayersRequest {
    return GetLayersRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetLayersRequest>): GetLayersRequest {
    const message = createBaseGetLayersRequest();
    message.layerIds = object.layerIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseGetLayersResponse(): GetLayersResponse {
  return { layers: [] };
}

export const GetLayersResponse: MessageFns<GetLayersResponse> = {
  encode(message: GetLayersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.layers) {
      Layer.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetLayersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetLayersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.layers.push(Layer.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetLayersResponse>): GetLayersResponse {
    return GetLayersResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetLayersResponse>): GetLayersResponse {
    const message = createBaseGetLayersResponse();
    message.layers = object.layers?.map((e) => Layer.fromPartial(e)) || [];
    return message;
  },
};

function createBaseErrorResponse(): ErrorResponse {
  return { code: 0 };
}

export const ErrorResponse: MessageFns<ErrorResponse> = {
  encode(message: ErrorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== 0) {
      writer.uint32(8).int32(message.code);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.code = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ErrorResponse>): ErrorResponse {
    return ErrorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ErrorResponse>): ErrorResponse {
    const message = createBaseErrorResponse();
    message.code = object.code ?? 0;
    return message;
  },
};

function createBaseSnapshot(): Snapshot {
  return {
    definitionVersion: 0,
    behaviorsFp: 0,
    defaultKeymapFp: 0,
    keymapFp: 0,
    physicalLayoutFp: 0,
    behaviorCount: 0,
    maxLayerNameLength: 0,
    availableLayers: 0,
    activeLayoutIndex: 0,
    layers: [],
    defFpBits: 0,
  };
}

export const Snapshot: MessageFns<Snapshot> = {
  encode(message: Snapshot, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.definitionVersion !== 0) {
      writer.uint32(8).uint32(message.definitionVersion);
    }
    if (message.behaviorsFp !== 0) {
      writer.uint32(16).uint32(message.behaviorsFp);
    }
    if (message.defaultKeymapFp !== 0) {
      writer.uint32(24).uint32(message.defaultKeymapFp);
    }
    if (message.keymapFp !== 0) {
      writer.uint32(32).uint32(message.keymapFp);
    }
    if (message.physicalLayoutFp !== 0) {
      writer.uint32(40).uint32(message.physicalLayoutFp);
    }
    if (message.behaviorCount !== 0) {
      writer.uint32(48).uint32(message.behaviorCount);
    }
    if (message.maxLayerNameLength !== 0) {
      writer.uint32(56).uint32(message.maxLayerNameLength);
    }
    if (message.availableLayers !== 0) {
      writer.uint32(64).uint32(message.availableLayers);
    }
    if (message.activeLayoutIndex !== 0) {
      writer.uint32(72).uint32(message.activeLayoutIndex);
    }
    for (const v of message.layers) {
      LayerFingerprint.encode(v!, writer.uint32(82).fork()).join();
    }
    if (message.defFpBits !== 0) {
      writer.uint32(88).uint32(message.defFpBits);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Snapshot {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSnapshot();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.definitionVersion = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.behaviorsFp = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.defaultKeymapFp = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.keymapFp = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.physicalLayoutFp = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.behaviorCount = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.maxLayerNameLength = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.availableLayers = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.activeLayoutIndex = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.layers.push(LayerFingerprint.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.defFpBits = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Snapshot>): Snapshot {
    return Snapshot.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Snapshot>): Snapshot {
    const message = createBaseSnapshot();
    message.definitionVersion = object.definitionVersion ?? 0;
    message.behaviorsFp = object.behaviorsFp ?? 0;
    message.defaultKeymapFp = object.defaultKeymapFp ?? 0;
    message.keymapFp = object.keymapFp ?? 0;
    message.physicalLayoutFp = object.physicalLayoutFp ?? 0;
    message.behaviorCount = object.behaviorCount ?? 0;
    message.maxLayerNameLength = object.maxLayerNameLength ?? 0;
    message.availableLayers = object.availableLayers ?? 0;
    message.activeLayoutIndex = object.activeLayoutIndex ?? 0;
    message.layers = object.layers?.map((e) => LayerFingerprint.fromPartial(e)) || [];
    message.defFpBits = object.defFpBits ?? 0;
    return message;
  },
};

function createBaseLayerFingerprint(): LayerFingerprint {
  return { id: 0, name: "", bindingCount: 0, fp: 0, defaultFp: 0, editedCount: 0 };
}

export const LayerFingerprint: MessageFns<LayerFingerprint> = {
  encode(message: LayerFingerprint, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.bindingCount !== 0) {
      writer.uint32(24).uint32(message.bindingCount);
    }
    if (message.fp !== 0) {
      writer.uint32(32).uint32(message.fp);
    }
    if (message.defaultFp !== 0) {
      writer.uint32(40).uint32(message.defaultFp);
    }
    if (message.editedCount !== 0) {
      writer.uint32(48).uint32(message.editedCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LayerFingerprint {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLayerFingerprint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.bindingCount = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.fp = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.defaultFp = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.editedCount = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<LayerFingerprint>): LayerFingerprint {
    return LayerFingerprint.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<LayerFingerprint>): LayerFingerprint {
    const message = createBaseLayerFingerprint();
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.bindingCount = object.bindingCount ?? 0;
    message.fp = object.fp ?? 0;
    message.defaultFp = object.defaultFp ?? 0;
    message.editedCount = object.editedCount ?? 0;
    return message;
  },
};

function createBaseListBehaviorsRequest(): ListBehaviorsRequest {
  return { details: 0, includeAlias: false, excludeDisplayName: false };
}

export const ListBehaviorsRequest: MessageFns<ListBehaviorsRequest> = {
  encode(message: ListBehaviorsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.details !== 0) {
      writer.uint32(8).int32(message.details);
    }
    if (message.includeAlias !== false) {
      writer.uint32(16).bool(message.includeAlias);
    }
    if (message.excludeDisplayName !== false) {
      writer.uint32(24).bool(message.excludeDisplayName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListBehaviorsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListBehaviorsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.details = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.includeAlias = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.excludeDisplayName = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListBehaviorsRequest>): ListBehaviorsRequest {
    return ListBehaviorsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListBehaviorsRequest>): ListBehaviorsRequest {
    const message = createBaseListBehaviorsRequest();
    message.details = object.details ?? 0;
    message.includeAlias = object.includeAlias ?? false;
    message.excludeDisplayName = object.excludeDisplayName ?? false;
    return message;
  },
};

function createBaseListBehaviorsResponse(): ListBehaviorsResponse {
  return { behaviors: [] };
}

export const ListBehaviorsResponse: MessageFns<ListBehaviorsResponse> = {
  encode(message: ListBehaviorsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.behaviors) {
      BehaviorSummary.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListBehaviorsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListBehaviorsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.behaviors.push(BehaviorSummary.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListBehaviorsResponse>): ListBehaviorsResponse {
    return ListBehaviorsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListBehaviorsResponse>): ListBehaviorsResponse {
    const message = createBaseListBehaviorsResponse();
    message.behaviors = object.behaviors?.map((e) => BehaviorSummary.fromPartial(e)) || [];
    return message;
  },
};

function createBaseBehaviorSummary(): BehaviorSummary {
  return { localId: 0, defFp: 0, details: undefined };
}

export const BehaviorSummary: MessageFns<BehaviorSummary> = {
  encode(message: BehaviorSummary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.localId !== 0) {
      writer.uint32(8).uint32(message.localId);
    }
    if (message.defFp !== 0) {
      writer.uint32(16).uint32(message.defFp);
    }
    if (message.details !== undefined) {
      BehaviorDetails.encode(message.details, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BehaviorSummary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBehaviorSummary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.localId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.defFp = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.details = BehaviorDetails.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<BehaviorSummary>): BehaviorSummary {
    return BehaviorSummary.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BehaviorSummary>): BehaviorSummary {
    const message = createBaseBehaviorSummary();
    message.localId = object.localId ?? 0;
    message.defFp = object.defFp ?? 0;
    message.details = (object.details !== undefined && object.details !== null)
      ? BehaviorDetails.fromPartial(object.details)
      : undefined;
    return message;
  },
};

function createBaseBehaviorDetails(): BehaviorDetails {
  return { displayName: "", alias: "", metadata: [] };
}

export const BehaviorDetails: MessageFns<BehaviorDetails> = {
  encode(message: BehaviorDetails, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.displayName !== "") {
      writer.uint32(10).string(message.displayName);
    }
    if (message.alias !== "") {
      writer.uint32(18).string(message.alias);
    }
    for (const v of message.metadata) {
      BehaviorBindingParametersSet.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BehaviorDetails {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBehaviorDetails();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.alias = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.metadata.push(BehaviorBindingParametersSet.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<BehaviorDetails>): BehaviorDetails {
    return BehaviorDetails.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BehaviorDetails>): BehaviorDetails {
    const message = createBaseBehaviorDetails();
    message.displayName = object.displayName ?? "";
    message.alias = object.alias ?? "";
    message.metadata = object.metadata?.map((e) => BehaviorBindingParametersSet.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetBehaviorsRequest(): GetBehaviorsRequest {
  return { behaviorIds: [], includeAlias: false, excludeDisplayName: false };
}

export const GetBehaviorsRequest: MessageFns<GetBehaviorsRequest> = {
  encode(message: GetBehaviorsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.behaviorIds) {
      writer.uint32(v);
    }
    writer.join();
    if (message.includeAlias !== false) {
      writer.uint32(16).bool(message.includeAlias);
    }
    if (message.excludeDisplayName !== false) {
      writer.uint32(24).bool(message.excludeDisplayName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBehaviorsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBehaviorsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.behaviorIds.push(reader.uint32());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.behaviorIds.push(reader.uint32());
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.includeAlias = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.excludeDisplayName = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetBehaviorsRequest>): GetBehaviorsRequest {
    return GetBehaviorsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetBehaviorsRequest>): GetBehaviorsRequest {
    const message = createBaseGetBehaviorsRequest();
    message.behaviorIds = object.behaviorIds?.map((e) => e) || [];
    message.includeAlias = object.includeAlias ?? false;
    message.excludeDisplayName = object.excludeDisplayName ?? false;
    return message;
  },
};

function createBaseGetBehaviorsResponse(): GetBehaviorsResponse {
  return { behaviors: [] };
}

export const GetBehaviorsResponse: MessageFns<GetBehaviorsResponse> = {
  encode(message: GetBehaviorsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.behaviors) {
      BehaviorEntry.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBehaviorsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBehaviorsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.behaviors.push(BehaviorEntry.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetBehaviorsResponse>): GetBehaviorsResponse {
    return GetBehaviorsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetBehaviorsResponse>): GetBehaviorsResponse {
    const message = createBaseGetBehaviorsResponse();
    message.behaviors = object.behaviors?.map((e) => BehaviorEntry.fromPartial(e)) || [];
    return message;
  },
};

function createBaseBehaviorEntry(): BehaviorEntry {
  return { id: 0, details: undefined };
}

export const BehaviorEntry: MessageFns<BehaviorEntry> = {
  encode(message: BehaviorEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    if (message.details !== undefined) {
      BehaviorDetails.encode(message.details, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BehaviorEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBehaviorEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.details = BehaviorDetails.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<BehaviorEntry>): BehaviorEntry {
    return BehaviorEntry.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BehaviorEntry>): BehaviorEntry {
    const message = createBaseBehaviorEntry();
    message.id = object.id ?? 0;
    message.details = (object.details !== undefined && object.details !== null)
      ? BehaviorDetails.fromPartial(object.details)
      : undefined;
    return message;
  },
};

function createBaseBehaviorBindingParametersSet(): BehaviorBindingParametersSet {
  return { param1: [], param2: [] };
}

export const BehaviorBindingParametersSet: MessageFns<BehaviorBindingParametersSet> = {
  encode(message: BehaviorBindingParametersSet, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.param1) {
      BehaviorParameterValueDescription.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.param2) {
      BehaviorParameterValueDescription.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BehaviorBindingParametersSet {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBehaviorBindingParametersSet();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.param1.push(BehaviorParameterValueDescription.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.param2.push(BehaviorParameterValueDescription.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<BehaviorBindingParametersSet>): BehaviorBindingParametersSet {
    return BehaviorBindingParametersSet.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BehaviorBindingParametersSet>): BehaviorBindingParametersSet {
    const message = createBaseBehaviorBindingParametersSet();
    message.param1 = object.param1?.map((e) => BehaviorParameterValueDescription.fromPartial(e)) || [];
    message.param2 = object.param2?.map((e) => BehaviorParameterValueDescription.fromPartial(e)) || [];
    return message;
  },
};

function createBaseBehaviorParameterValueDescriptionRange(): BehaviorParameterValueDescriptionRange {
  return { min: 0, max: 0 };
}

export const BehaviorParameterValueDescriptionRange: MessageFns<BehaviorParameterValueDescriptionRange> = {
  encode(message: BehaviorParameterValueDescriptionRange, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.min !== 0) {
      writer.uint32(8).int32(message.min);
    }
    if (message.max !== 0) {
      writer.uint32(16).int32(message.max);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BehaviorParameterValueDescriptionRange {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBehaviorParameterValueDescriptionRange();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.min = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.max = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<BehaviorParameterValueDescriptionRange>): BehaviorParameterValueDescriptionRange {
    return BehaviorParameterValueDescriptionRange.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BehaviorParameterValueDescriptionRange>): BehaviorParameterValueDescriptionRange {
    const message = createBaseBehaviorParameterValueDescriptionRange();
    message.min = object.min ?? 0;
    message.max = object.max ?? 0;
    return message;
  },
};

function createBaseBehaviorParameterNil(): BehaviorParameterNil {
  return {};
}

export const BehaviorParameterNil: MessageFns<BehaviorParameterNil> = {
  encode(_: BehaviorParameterNil, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BehaviorParameterNil {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBehaviorParameterNil();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<BehaviorParameterNil>): BehaviorParameterNil {
    return BehaviorParameterNil.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<BehaviorParameterNil>): BehaviorParameterNil {
    const message = createBaseBehaviorParameterNil();
    return message;
  },
};

function createBaseBehaviorParameterLayerId(): BehaviorParameterLayerId {
  return {};
}

export const BehaviorParameterLayerId: MessageFns<BehaviorParameterLayerId> = {
  encode(_: BehaviorParameterLayerId, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BehaviorParameterLayerId {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBehaviorParameterLayerId();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<BehaviorParameterLayerId>): BehaviorParameterLayerId {
    return BehaviorParameterLayerId.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<BehaviorParameterLayerId>): BehaviorParameterLayerId {
    const message = createBaseBehaviorParameterLayerId();
    return message;
  },
};

function createBaseBehaviorParameterHidUsage(): BehaviorParameterHidUsage {
  return { keyboardMax: 0, consumerMax: 0 };
}

export const BehaviorParameterHidUsage: MessageFns<BehaviorParameterHidUsage> = {
  encode(message: BehaviorParameterHidUsage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.keyboardMax !== 0) {
      writer.uint32(8).uint32(message.keyboardMax);
    }
    if (message.consumerMax !== 0) {
      writer.uint32(16).uint32(message.consumerMax);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BehaviorParameterHidUsage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBehaviorParameterHidUsage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.keyboardMax = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.consumerMax = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<BehaviorParameterHidUsage>): BehaviorParameterHidUsage {
    return BehaviorParameterHidUsage.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BehaviorParameterHidUsage>): BehaviorParameterHidUsage {
    const message = createBaseBehaviorParameterHidUsage();
    message.keyboardMax = object.keyboardMax ?? 0;
    message.consumerMax = object.consumerMax ?? 0;
    return message;
  },
};

function createBaseBehaviorParameterValueDescription(): BehaviorParameterValueDescription {
  return { name: "", nil: undefined, constant: undefined, range: undefined, hidUsage: undefined, layerId: undefined };
}

export const BehaviorParameterValueDescription: MessageFns<BehaviorParameterValueDescription> = {
  encode(message: BehaviorParameterValueDescription, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.nil !== undefined) {
      BehaviorParameterNil.encode(message.nil, writer.uint32(18).fork()).join();
    }
    if (message.constant !== undefined) {
      writer.uint32(24).uint32(message.constant);
    }
    if (message.range !== undefined) {
      BehaviorParameterValueDescriptionRange.encode(message.range, writer.uint32(34).fork()).join();
    }
    if (message.hidUsage !== undefined) {
      BehaviorParameterHidUsage.encode(message.hidUsage, writer.uint32(42).fork()).join();
    }
    if (message.layerId !== undefined) {
      BehaviorParameterLayerId.encode(message.layerId, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BehaviorParameterValueDescription {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBehaviorParameterValueDescription();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nil = BehaviorParameterNil.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.constant = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.range = BehaviorParameterValueDescriptionRange.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.hidUsage = BehaviorParameterHidUsage.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.layerId = BehaviorParameterLayerId.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<BehaviorParameterValueDescription>): BehaviorParameterValueDescription {
    return BehaviorParameterValueDescription.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BehaviorParameterValueDescription>): BehaviorParameterValueDescription {
    const message = createBaseBehaviorParameterValueDescription();
    message.name = object.name ?? "";
    message.nil = (object.nil !== undefined && object.nil !== null)
      ? BehaviorParameterNil.fromPartial(object.nil)
      : undefined;
    message.constant = object.constant ?? undefined;
    message.range = (object.range !== undefined && object.range !== null)
      ? BehaviorParameterValueDescriptionRange.fromPartial(object.range)
      : undefined;
    message.hidUsage = (object.hidUsage !== undefined && object.hidUsage !== null)
      ? BehaviorParameterHidUsage.fromPartial(object.hidUsage)
      : undefined;
    message.layerId = (object.layerId !== undefined && object.layerId !== null)
      ? BehaviorParameterLayerId.fromPartial(object.layerId)
      : undefined;
    return message;
  },
};

function createBaseBehaviorBinding(): BehaviorBinding {
  return { behaviorId: 0, param1: 0, param2: 0 };
}

export const BehaviorBinding: MessageFns<BehaviorBinding> = {
  encode(message: BehaviorBinding, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.behaviorId !== 0) {
      writer.uint32(8).sint32(message.behaviorId);
    }
    if (message.param1 !== 0) {
      writer.uint32(16).uint32(message.param1);
    }
    if (message.param2 !== 0) {
      writer.uint32(24).uint32(message.param2);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BehaviorBinding {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBehaviorBinding();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.behaviorId = reader.sint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.param1 = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.param2 = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<BehaviorBinding>): BehaviorBinding {
    return BehaviorBinding.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BehaviorBinding>): BehaviorBinding {
    const message = createBaseBehaviorBinding();
    message.behaviorId = object.behaviorId ?? 0;
    message.param1 = object.param1 ?? 0;
    message.param2 = object.param2 ?? 0;
    return message;
  },
};

function createBaseLayer(): Layer {
  return { id: 0, name: "", bindings: [] };
}

export const Layer: MessageFns<Layer> = {
  encode(message: Layer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    for (const v of message.bindings) {
      BehaviorBinding.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Layer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLayer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.bindings.push(BehaviorBinding.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Layer>): Layer {
    return Layer.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Layer>): Layer {
    const message = createBaseLayer();
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.bindings = object.bindings?.map((e) => BehaviorBinding.fromPartial(e)) || [];
    return message;
  },
};

function createBaseEditedBinding(): EditedBinding {
  return { position: 0, binding: undefined };
}

export const EditedBinding: MessageFns<EditedBinding> = {
  encode(message: EditedBinding, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.position !== 0) {
      writer.uint32(8).uint32(message.position);
    }
    if (message.binding !== undefined) {
      BehaviorBinding.encode(message.binding, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EditedBinding {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEditedBinding();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.position = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.binding = BehaviorBinding.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<EditedBinding>): EditedBinding {
    return EditedBinding.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EditedBinding>): EditedBinding {
    const message = createBaseEditedBinding();
    message.position = object.position ?? 0;
    message.binding = (object.binding !== undefined && object.binding !== null)
      ? BehaviorBinding.fromPartial(object.binding)
      : undefined;
    return message;
  },
};

function createBaseEditedLayer(): EditedLayer {
  return { id: 0, bindings: [] };
}

export const EditedLayer: MessageFns<EditedLayer> = {
  encode(message: EditedLayer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    for (const v of message.bindings) {
      EditedBinding.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EditedLayer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEditedLayer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.bindings.push(EditedBinding.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<EditedLayer>): EditedLayer {
    return EditedLayer.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EditedLayer>): EditedLayer {
    const message = createBaseEditedLayer();
    message.id = object.id ?? 0;
    message.bindings = object.bindings?.map((e) => EditedBinding.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetPhysicalLayoutsRequest(): GetPhysicalLayoutsRequest {
  return { details: 0 };
}

export const GetPhysicalLayoutsRequest: MessageFns<GetPhysicalLayoutsRequest> = {
  encode(message: GetPhysicalLayoutsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.details !== 0) {
      writer.uint32(8).int32(message.details);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPhysicalLayoutsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPhysicalLayoutsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.details = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetPhysicalLayoutsRequest>): GetPhysicalLayoutsRequest {
    return GetPhysicalLayoutsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetPhysicalLayoutsRequest>): GetPhysicalLayoutsRequest {
    const message = createBaseGetPhysicalLayoutsRequest();
    message.details = object.details ?? 0;
    return message;
  },
};

function createBaseGetPhysicalLayoutRequest(): GetPhysicalLayoutRequest {
  return { layoutIndex: 0 };
}

export const GetPhysicalLayoutRequest: MessageFns<GetPhysicalLayoutRequest> = {
  encode(message: GetPhysicalLayoutRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.layoutIndex !== 0) {
      writer.uint32(8).uint32(message.layoutIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPhysicalLayoutRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPhysicalLayoutRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.layoutIndex = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetPhysicalLayoutRequest>): GetPhysicalLayoutRequest {
    return GetPhysicalLayoutRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetPhysicalLayoutRequest>): GetPhysicalLayoutRequest {
    const message = createBaseGetPhysicalLayoutRequest();
    message.layoutIndex = object.layoutIndex ?? 0;
    return message;
  },
};

function createBasePhysicalLayoutsResponse(): PhysicalLayoutsResponse {
  return { activeLayoutIndex: 0, layouts: [] };
}

export const PhysicalLayoutsResponse: MessageFns<PhysicalLayoutsResponse> = {
  encode(message: PhysicalLayoutsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.activeLayoutIndex !== 0) {
      writer.uint32(8).uint32(message.activeLayoutIndex);
    }
    for (const v of message.layouts) {
      PhysicalLayoutSummary.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PhysicalLayoutsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePhysicalLayoutsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.activeLayoutIndex = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.layouts.push(PhysicalLayoutSummary.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<PhysicalLayoutsResponse>): PhysicalLayoutsResponse {
    return PhysicalLayoutsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PhysicalLayoutsResponse>): PhysicalLayoutsResponse {
    const message = createBasePhysicalLayoutsResponse();
    message.activeLayoutIndex = object.activeLayoutIndex ?? 0;
    message.layouts = object.layouts?.map((e) => PhysicalLayoutSummary.fromPartial(e)) || [];
    return message;
  },
};

function createBasePhysicalLayoutResponse(): PhysicalLayoutResponse {
  return { index: 0, layout: undefined };
}

export const PhysicalLayoutResponse: MessageFns<PhysicalLayoutResponse> = {
  encode(message: PhysicalLayoutResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.index !== 0) {
      writer.uint32(8).uint32(message.index);
    }
    if (message.layout !== undefined) {
      PhysicalLayoutSummary.encode(message.layout, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PhysicalLayoutResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePhysicalLayoutResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.index = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.layout = PhysicalLayoutSummary.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<PhysicalLayoutResponse>): PhysicalLayoutResponse {
    return PhysicalLayoutResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PhysicalLayoutResponse>): PhysicalLayoutResponse {
    const message = createBasePhysicalLayoutResponse();
    message.index = object.index ?? 0;
    message.layout = (object.layout !== undefined && object.layout !== null)
      ? PhysicalLayoutSummary.fromPartial(object.layout)
      : undefined;
    return message;
  },
};

function createBasePhysicalLayoutSummary(): PhysicalLayoutSummary {
  return { name: "", fp: 0, keys: [], defaultWidth: 0, defaultHeight: 0 };
}

export const PhysicalLayoutSummary: MessageFns<PhysicalLayoutSummary> = {
  encode(message: PhysicalLayoutSummary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.fp !== 0) {
      writer.uint32(16).uint32(message.fp);
    }
    for (const v of message.keys) {
      KeyPhysicalAttrs.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.defaultWidth !== 0) {
      writer.uint32(32).sint32(message.defaultWidth);
    }
    if (message.defaultHeight !== 0) {
      writer.uint32(40).sint32(message.defaultHeight);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PhysicalLayoutSummary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePhysicalLayoutSummary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.fp = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.keys.push(KeyPhysicalAttrs.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.defaultWidth = reader.sint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.defaultHeight = reader.sint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<PhysicalLayoutSummary>): PhysicalLayoutSummary {
    return PhysicalLayoutSummary.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PhysicalLayoutSummary>): PhysicalLayoutSummary {
    const message = createBasePhysicalLayoutSummary();
    message.name = object.name ?? "";
    message.fp = object.fp ?? 0;
    message.keys = object.keys?.map((e) => KeyPhysicalAttrs.fromPartial(e)) || [];
    message.defaultWidth = object.defaultWidth ?? 0;
    message.defaultHeight = object.defaultHeight ?? 0;
    return message;
  },
};

function createBaseKeyPhysicalAttrs(): KeyPhysicalAttrs {
  return { width: 0, height: 0, x: 0, y: 0, r: 0, rx: 0, ry: 0 };
}

export const KeyPhysicalAttrs: MessageFns<KeyPhysicalAttrs> = {
  encode(message: KeyPhysicalAttrs, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.width !== 0) {
      writer.uint32(8).sint32(message.width);
    }
    if (message.height !== 0) {
      writer.uint32(16).sint32(message.height);
    }
    if (message.x !== 0) {
      writer.uint32(24).sint32(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(32).sint32(message.y);
    }
    if (message.r !== 0) {
      writer.uint32(40).sint32(message.r);
    }
    if (message.rx !== 0) {
      writer.uint32(48).sint32(message.rx);
    }
    if (message.ry !== 0) {
      writer.uint32(56).sint32(message.ry);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): KeyPhysicalAttrs {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeyPhysicalAttrs();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.width = reader.sint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.height = reader.sint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.x = reader.sint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.y = reader.sint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.r = reader.sint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.rx = reader.sint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.ry = reader.sint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<KeyPhysicalAttrs>): KeyPhysicalAttrs {
    return KeyPhysicalAttrs.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<KeyPhysicalAttrs>): KeyPhysicalAttrs {
    const message = createBaseKeyPhysicalAttrs();
    message.width = object.width ?? 0;
    message.height = object.height ?? 0;
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    message.r = object.r ?? 0;
    message.rx = object.rx ?? 0;
    message.ry = object.ry ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
