// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: zmk/physical_layouts/physical_layouts.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cormoran.zmk.physical_layouts";

export interface GetPhysicalLayoutRequest {
}

export interface PointSizePhysicalAttrs {
  x: number;
  y: number;
  size: number;
}

export interface RectPhysicalAttrs {
  width: number;
  height: number;
  x: number;
  y: number;
  r: number;
  rx: number;
  ry: number;
}

export interface LinkedDevice {
  deviceIdentifier: string;
  subsystemIdentifier: string;
}

export interface Trackball {
  attrs: PointSizePhysicalAttrs | undefined;
}

export interface RotaryEncoder {
  enabled: boolean;
  attrs: PointSizePhysicalAttrs | undefined;
}

export interface TouchPad {
  attrs: RectPhysicalAttrs | undefined;
}

export interface CustomModule {
  type: string;
  attrs: RectPhysicalAttrs | undefined;
}

export interface PhysicalDevice {
  identifier: string;
  displayName: string;
  links: LinkedDevice[];
  enabled: boolean;
  trackball?: Trackball | undefined;
  touchPad?: TouchPad | undefined;
  customModule?: CustomModule | undefined;
}

export interface GetPhysicalLayoutResponse {
  devices: PhysicalDevice[];
  rotaryEncoders: RotaryEncoder[];
}

export interface Request {
  getPhysicalLayout?: GetPhysicalLayoutRequest | undefined;
}

export interface ErrorResponse {
  message: string;
}

export interface Response {
  error?: ErrorResponse | undefined;
  physicalLayout?: GetPhysicalLayoutResponse | undefined;
}

function createBaseGetPhysicalLayoutRequest(): GetPhysicalLayoutRequest {
  return {};
}

export const GetPhysicalLayoutRequest: MessageFns<GetPhysicalLayoutRequest> = {
  encode(_: GetPhysicalLayoutRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPhysicalLayoutRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPhysicalLayoutRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetPhysicalLayoutRequest>): GetPhysicalLayoutRequest {
    return GetPhysicalLayoutRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<GetPhysicalLayoutRequest>): GetPhysicalLayoutRequest {
    const message = createBaseGetPhysicalLayoutRequest();
    return message;
  },
};

function createBasePointSizePhysicalAttrs(): PointSizePhysicalAttrs {
  return { x: 0, y: 0, size: 0 };
}

export const PointSizePhysicalAttrs: MessageFns<PointSizePhysicalAttrs> = {
  encode(message: PointSizePhysicalAttrs, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.x !== 0) {
      writer.uint32(8).int32(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(16).int32(message.y);
    }
    if (message.size !== 0) {
      writer.uint32(24).int32(message.size);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PointSizePhysicalAttrs {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePointSizePhysicalAttrs();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.x = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.y = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.size = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<PointSizePhysicalAttrs>): PointSizePhysicalAttrs {
    return PointSizePhysicalAttrs.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PointSizePhysicalAttrs>): PointSizePhysicalAttrs {
    const message = createBasePointSizePhysicalAttrs();
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    message.size = object.size ?? 0;
    return message;
  },
};

function createBaseRectPhysicalAttrs(): RectPhysicalAttrs {
  return { width: 0, height: 0, x: 0, y: 0, r: 0, rx: 0, ry: 0 };
}

export const RectPhysicalAttrs: MessageFns<RectPhysicalAttrs> = {
  encode(message: RectPhysicalAttrs, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.width !== 0) {
      writer.uint32(8).int32(message.width);
    }
    if (message.height !== 0) {
      writer.uint32(16).int32(message.height);
    }
    if (message.x !== 0) {
      writer.uint32(24).int32(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(32).int32(message.y);
    }
    if (message.r !== 0) {
      writer.uint32(40).int32(message.r);
    }
    if (message.rx !== 0) {
      writer.uint32(48).int32(message.rx);
    }
    if (message.ry !== 0) {
      writer.uint32(56).int32(message.ry);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RectPhysicalAttrs {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRectPhysicalAttrs();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.width = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.height = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.x = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.y = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.r = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.rx = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.ry = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<RectPhysicalAttrs>): RectPhysicalAttrs {
    return RectPhysicalAttrs.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RectPhysicalAttrs>): RectPhysicalAttrs {
    const message = createBaseRectPhysicalAttrs();
    message.width = object.width ?? 0;
    message.height = object.height ?? 0;
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    message.r = object.r ?? 0;
    message.rx = object.rx ?? 0;
    message.ry = object.ry ?? 0;
    return message;
  },
};

function createBaseLinkedDevice(): LinkedDevice {
  return { deviceIdentifier: "", subsystemIdentifier: "" };
}

export const LinkedDevice: MessageFns<LinkedDevice> = {
  encode(message: LinkedDevice, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deviceIdentifier !== "") {
      writer.uint32(10).string(message.deviceIdentifier);
    }
    if (message.subsystemIdentifier !== "") {
      writer.uint32(18).string(message.subsystemIdentifier);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LinkedDevice {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLinkedDevice();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.deviceIdentifier = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.subsystemIdentifier = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<LinkedDevice>): LinkedDevice {
    return LinkedDevice.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<LinkedDevice>): LinkedDevice {
    const message = createBaseLinkedDevice();
    message.deviceIdentifier = object.deviceIdentifier ?? "";
    message.subsystemIdentifier = object.subsystemIdentifier ?? "";
    return message;
  },
};

function createBaseTrackball(): Trackball {
  return { attrs: undefined };
}

export const Trackball: MessageFns<Trackball> = {
  encode(message: Trackball, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.attrs !== undefined) {
      PointSizePhysicalAttrs.encode(message.attrs, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Trackball {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrackball();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.attrs = PointSizePhysicalAttrs.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Trackball>): Trackball {
    return Trackball.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Trackball>): Trackball {
    const message = createBaseTrackball();
    message.attrs = (object.attrs !== undefined && object.attrs !== null)
      ? PointSizePhysicalAttrs.fromPartial(object.attrs)
      : undefined;
    return message;
  },
};

function createBaseRotaryEncoder(): RotaryEncoder {
  return { enabled: false, attrs: undefined };
}

export const RotaryEncoder: MessageFns<RotaryEncoder> = {
  encode(message: RotaryEncoder, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.enabled !== false) {
      writer.uint32(8).bool(message.enabled);
    }
    if (message.attrs !== undefined) {
      PointSizePhysicalAttrs.encode(message.attrs, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RotaryEncoder {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRotaryEncoder();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.attrs = PointSizePhysicalAttrs.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<RotaryEncoder>): RotaryEncoder {
    return RotaryEncoder.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RotaryEncoder>): RotaryEncoder {
    const message = createBaseRotaryEncoder();
    message.enabled = object.enabled ?? false;
    message.attrs = (object.attrs !== undefined && object.attrs !== null)
      ? PointSizePhysicalAttrs.fromPartial(object.attrs)
      : undefined;
    return message;
  },
};

function createBaseTouchPad(): TouchPad {
  return { attrs: undefined };
}

export const TouchPad: MessageFns<TouchPad> = {
  encode(message: TouchPad, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.attrs !== undefined) {
      RectPhysicalAttrs.encode(message.attrs, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TouchPad {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTouchPad();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.attrs = RectPhysicalAttrs.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<TouchPad>): TouchPad {
    return TouchPad.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TouchPad>): TouchPad {
    const message = createBaseTouchPad();
    message.attrs = (object.attrs !== undefined && object.attrs !== null)
      ? RectPhysicalAttrs.fromPartial(object.attrs)
      : undefined;
    return message;
  },
};

function createBaseCustomModule(): CustomModule {
  return { type: "", attrs: undefined };
}

export const CustomModule: MessageFns<CustomModule> = {
  encode(message: CustomModule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.attrs !== undefined) {
      RectPhysicalAttrs.encode(message.attrs, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CustomModule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCustomModule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.attrs = RectPhysicalAttrs.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CustomModule>): CustomModule {
    return CustomModule.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CustomModule>): CustomModule {
    const message = createBaseCustomModule();
    message.type = object.type ?? "";
    message.attrs = (object.attrs !== undefined && object.attrs !== null)
      ? RectPhysicalAttrs.fromPartial(object.attrs)
      : undefined;
    return message;
  },
};

function createBasePhysicalDevice(): PhysicalDevice {
  return {
    identifier: "",
    displayName: "",
    links: [],
    enabled: false,
    trackball: undefined,
    touchPad: undefined,
    customModule: undefined,
  };
}

export const PhysicalDevice: MessageFns<PhysicalDevice> = {
  encode(message: PhysicalDevice, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.identifier !== "") {
      writer.uint32(10).string(message.identifier);
    }
    if (message.displayName !== "") {
      writer.uint32(18).string(message.displayName);
    }
    for (const v of message.links) {
      LinkedDevice.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.enabled !== false) {
      writer.uint32(64).bool(message.enabled);
    }
    if (message.trackball !== undefined) {
      Trackball.encode(message.trackball, writer.uint32(34).fork()).join();
    }
    if (message.touchPad !== undefined) {
      TouchPad.encode(message.touchPad, writer.uint32(50).fork()).join();
    }
    if (message.customModule !== undefined) {
      CustomModule.encode(message.customModule, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PhysicalDevice {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePhysicalDevice();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.identifier = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.links.push(LinkedDevice.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.trackball = Trackball.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.touchPad = TouchPad.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.customModule = CustomModule.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<PhysicalDevice>): PhysicalDevice {
    return PhysicalDevice.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PhysicalDevice>): PhysicalDevice {
    const message = createBasePhysicalDevice();
    message.identifier = object.identifier ?? "";
    message.displayName = object.displayName ?? "";
    message.links = object.links?.map((e) => LinkedDevice.fromPartial(e)) || [];
    message.enabled = object.enabled ?? false;
    message.trackball = (object.trackball !== undefined && object.trackball !== null)
      ? Trackball.fromPartial(object.trackball)
      : undefined;
    message.touchPad = (object.touchPad !== undefined && object.touchPad !== null)
      ? TouchPad.fromPartial(object.touchPad)
      : undefined;
    message.customModule = (object.customModule !== undefined && object.customModule !== null)
      ? CustomModule.fromPartial(object.customModule)
      : undefined;
    return message;
  },
};

function createBaseGetPhysicalLayoutResponse(): GetPhysicalLayoutResponse {
  return { devices: [], rotaryEncoders: [] };
}

export const GetPhysicalLayoutResponse: MessageFns<GetPhysicalLayoutResponse> = {
  encode(message: GetPhysicalLayoutResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.devices) {
      PhysicalDevice.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.rotaryEncoders) {
      RotaryEncoder.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPhysicalLayoutResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPhysicalLayoutResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.devices.push(PhysicalDevice.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.rotaryEncoders.push(RotaryEncoder.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetPhysicalLayoutResponse>): GetPhysicalLayoutResponse {
    return GetPhysicalLayoutResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetPhysicalLayoutResponse>): GetPhysicalLayoutResponse {
    const message = createBaseGetPhysicalLayoutResponse();
    message.devices = object.devices?.map((e) => PhysicalDevice.fromPartial(e)) || [];
    message.rotaryEncoders = object.rotaryEncoders?.map((e) => RotaryEncoder.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRequest(): Request {
  return { getPhysicalLayout: undefined };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.getPhysicalLayout !== undefined) {
      GetPhysicalLayoutRequest.encode(message.getPhysicalLayout, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.getPhysicalLayout = GetPhysicalLayoutRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Request>): Request {
    return Request.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Request>): Request {
    const message = createBaseRequest();
    message.getPhysicalLayout = (object.getPhysicalLayout !== undefined && object.getPhysicalLayout !== null)
      ? GetPhysicalLayoutRequest.fromPartial(object.getPhysicalLayout)
      : undefined;
    return message;
  },
};

function createBaseErrorResponse(): ErrorResponse {
  return { message: "" };
}

export const ErrorResponse: MessageFns<ErrorResponse> = {
  encode(message: ErrorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ErrorResponse>): ErrorResponse {
    return ErrorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ErrorResponse>): ErrorResponse {
    const message = createBaseErrorResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseResponse(): Response {
  return { error: undefined, physicalLayout: undefined };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(10).fork()).join();
    }
    if (message.physicalLayout !== undefined) {
      GetPhysicalLayoutResponse.encode(message.physicalLayout, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.physicalLayout = GetPhysicalLayoutResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Response>): Response {
    return Response.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Response>): Response {
    const message = createBaseResponse();
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    message.physicalLayout = (object.physicalLayout !== undefined && object.physicalLayout !== null)
      ? GetPhysicalLayoutResponse.fromPartial(object.physicalLayout)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
