// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: zmk/runtime_sensor_rotate/runtime_sensor_rotate.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cormoran.rsr";

/** Runtime sensor rotate messages */
export interface Binding {
  behaviorId: number;
  param1: number;
  param2: number;
  tapMs: number;
}

export interface SetLayerBindingsRequest {
  sensorIndex: number;
  layer: number;
  cwBinding: Binding | undefined;
  ccwBinding: Binding | undefined;
}

export interface SetLayerBindingsResponse {
  success: boolean;
}

export interface GetAllLayerBindingsRequest {
  sensorIndex: number;
}

export interface LayerBindings {
  layer: number;
  cwBinding: Binding | undefined;
  ccwBinding: Binding | undefined;
}

export interface GetAllLayerBindingsResponse {
  bindings: LayerBindings[];
}

export interface GetSensorsRequest {
}

export interface SensorInfo {
  index: number;
  name: string;
}

export interface GetSensorsResponse {
  sensors: SensorInfo[];
}

export interface Request {
  setLayerBindings?: SetLayerBindingsRequest | undefined;
  getAllLayerBindings?: GetAllLayerBindingsRequest | undefined;
  getSensors?: GetSensorsRequest | undefined;
}

export interface ErrorResponse {
  message: string;
}

export interface Response {
  error?: ErrorResponse | undefined;
  setLayerBindings?: SetLayerBindingsResponse | undefined;
  getAllLayerBindings?: GetAllLayerBindingsResponse | undefined;
  getSensors?: GetSensorsResponse | undefined;
}

function createBaseBinding(): Binding {
  return { behaviorId: 0, param1: 0, param2: 0, tapMs: 0 };
}

export const Binding: MessageFns<Binding> = {
  encode(message: Binding, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.behaviorId !== 0) {
      writer.uint32(8).uint32(message.behaviorId);
    }
    if (message.param1 !== 0) {
      writer.uint32(16).uint32(message.param1);
    }
    if (message.param2 !== 0) {
      writer.uint32(24).uint32(message.param2);
    }
    if (message.tapMs !== 0) {
      writer.uint32(32).uint32(message.tapMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Binding {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBinding();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.behaviorId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.param1 = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.param2 = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.tapMs = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Binding>): Binding {
    return Binding.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Binding>): Binding {
    const message = createBaseBinding();
    message.behaviorId = object.behaviorId ?? 0;
    message.param1 = object.param1 ?? 0;
    message.param2 = object.param2 ?? 0;
    message.tapMs = object.tapMs ?? 0;
    return message;
  },
};

function createBaseSetLayerBindingsRequest(): SetLayerBindingsRequest {
  return { sensorIndex: 0, layer: 0, cwBinding: undefined, ccwBinding: undefined };
}

export const SetLayerBindingsRequest: MessageFns<SetLayerBindingsRequest> = {
  encode(message: SetLayerBindingsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sensorIndex !== 0) {
      writer.uint32(8).uint32(message.sensorIndex);
    }
    if (message.layer !== 0) {
      writer.uint32(16).uint32(message.layer);
    }
    if (message.cwBinding !== undefined) {
      Binding.encode(message.cwBinding, writer.uint32(26).fork()).join();
    }
    if (message.ccwBinding !== undefined) {
      Binding.encode(message.ccwBinding, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetLayerBindingsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetLayerBindingsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.sensorIndex = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.layer = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.cwBinding = Binding.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.ccwBinding = Binding.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetLayerBindingsRequest>): SetLayerBindingsRequest {
    return SetLayerBindingsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetLayerBindingsRequest>): SetLayerBindingsRequest {
    const message = createBaseSetLayerBindingsRequest();
    message.sensorIndex = object.sensorIndex ?? 0;
    message.layer = object.layer ?? 0;
    message.cwBinding = (object.cwBinding !== undefined && object.cwBinding !== null)
      ? Binding.fromPartial(object.cwBinding)
      : undefined;
    message.ccwBinding = (object.ccwBinding !== undefined && object.ccwBinding !== null)
      ? Binding.fromPartial(object.ccwBinding)
      : undefined;
    return message;
  },
};

function createBaseSetLayerBindingsResponse(): SetLayerBindingsResponse {
  return { success: false };
}

export const SetLayerBindingsResponse: MessageFns<SetLayerBindingsResponse> = {
  encode(message: SetLayerBindingsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetLayerBindingsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetLayerBindingsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetLayerBindingsResponse>): SetLayerBindingsResponse {
    return SetLayerBindingsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetLayerBindingsResponse>): SetLayerBindingsResponse {
    const message = createBaseSetLayerBindingsResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseGetAllLayerBindingsRequest(): GetAllLayerBindingsRequest {
  return { sensorIndex: 0 };
}

export const GetAllLayerBindingsRequest: MessageFns<GetAllLayerBindingsRequest> = {
  encode(message: GetAllLayerBindingsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sensorIndex !== 0) {
      writer.uint32(8).uint32(message.sensorIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAllLayerBindingsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAllLayerBindingsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.sensorIndex = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetAllLayerBindingsRequest>): GetAllLayerBindingsRequest {
    return GetAllLayerBindingsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetAllLayerBindingsRequest>): GetAllLayerBindingsRequest {
    const message = createBaseGetAllLayerBindingsRequest();
    message.sensorIndex = object.sensorIndex ?? 0;
    return message;
  },
};

function createBaseLayerBindings(): LayerBindings {
  return { layer: 0, cwBinding: undefined, ccwBinding: undefined };
}

export const LayerBindings: MessageFns<LayerBindings> = {
  encode(message: LayerBindings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.layer !== 0) {
      writer.uint32(8).uint32(message.layer);
    }
    if (message.cwBinding !== undefined) {
      Binding.encode(message.cwBinding, writer.uint32(18).fork()).join();
    }
    if (message.ccwBinding !== undefined) {
      Binding.encode(message.ccwBinding, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LayerBindings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLayerBindings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.layer = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cwBinding = Binding.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ccwBinding = Binding.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<LayerBindings>): LayerBindings {
    return LayerBindings.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<LayerBindings>): LayerBindings {
    const message = createBaseLayerBindings();
    message.layer = object.layer ?? 0;
    message.cwBinding = (object.cwBinding !== undefined && object.cwBinding !== null)
      ? Binding.fromPartial(object.cwBinding)
      : undefined;
    message.ccwBinding = (object.ccwBinding !== undefined && object.ccwBinding !== null)
      ? Binding.fromPartial(object.ccwBinding)
      : undefined;
    return message;
  },
};

function createBaseGetAllLayerBindingsResponse(): GetAllLayerBindingsResponse {
  return { bindings: [] };
}

export const GetAllLayerBindingsResponse: MessageFns<GetAllLayerBindingsResponse> = {
  encode(message: GetAllLayerBindingsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.bindings) {
      LayerBindings.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAllLayerBindingsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAllLayerBindingsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bindings.push(LayerBindings.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetAllLayerBindingsResponse>): GetAllLayerBindingsResponse {
    return GetAllLayerBindingsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetAllLayerBindingsResponse>): GetAllLayerBindingsResponse {
    const message = createBaseGetAllLayerBindingsResponse();
    message.bindings = object.bindings?.map((e) => LayerBindings.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetSensorsRequest(): GetSensorsRequest {
  return {};
}

export const GetSensorsRequest: MessageFns<GetSensorsRequest> = {
  encode(_: GetSensorsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSensorsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSensorsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetSensorsRequest>): GetSensorsRequest {
    return GetSensorsRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<GetSensorsRequest>): GetSensorsRequest {
    const message = createBaseGetSensorsRequest();
    return message;
  },
};

function createBaseSensorInfo(): SensorInfo {
  return { index: 0, name: "" };
}

export const SensorInfo: MessageFns<SensorInfo> = {
  encode(message: SensorInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.index !== 0) {
      writer.uint32(8).uint32(message.index);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SensorInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSensorInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.index = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SensorInfo>): SensorInfo {
    return SensorInfo.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SensorInfo>): SensorInfo {
    const message = createBaseSensorInfo();
    message.index = object.index ?? 0;
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseGetSensorsResponse(): GetSensorsResponse {
  return { sensors: [] };
}

export const GetSensorsResponse: MessageFns<GetSensorsResponse> = {
  encode(message: GetSensorsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.sensors) {
      SensorInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSensorsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSensorsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sensors.push(SensorInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetSensorsResponse>): GetSensorsResponse {
    return GetSensorsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetSensorsResponse>): GetSensorsResponse {
    const message = createBaseGetSensorsResponse();
    message.sensors = object.sensors?.map((e) => SensorInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRequest(): Request {
  return { setLayerBindings: undefined, getAllLayerBindings: undefined, getSensors: undefined };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.setLayerBindings !== undefined) {
      SetLayerBindingsRequest.encode(message.setLayerBindings, writer.uint32(10).fork()).join();
    }
    if (message.getAllLayerBindings !== undefined) {
      GetAllLayerBindingsRequest.encode(message.getAllLayerBindings, writer.uint32(18).fork()).join();
    }
    if (message.getSensors !== undefined) {
      GetSensorsRequest.encode(message.getSensors, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.setLayerBindings = SetLayerBindingsRequest.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.getAllLayerBindings = GetAllLayerBindingsRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.getSensors = GetSensorsRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Request>): Request {
    return Request.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Request>): Request {
    const message = createBaseRequest();
    message.setLayerBindings = (object.setLayerBindings !== undefined && object.setLayerBindings !== null)
      ? SetLayerBindingsRequest.fromPartial(object.setLayerBindings)
      : undefined;
    message.getAllLayerBindings = (object.getAllLayerBindings !== undefined && object.getAllLayerBindings !== null)
      ? GetAllLayerBindingsRequest.fromPartial(object.getAllLayerBindings)
      : undefined;
    message.getSensors = (object.getSensors !== undefined && object.getSensors !== null)
      ? GetSensorsRequest.fromPartial(object.getSensors)
      : undefined;
    return message;
  },
};

function createBaseErrorResponse(): ErrorResponse {
  return { message: "" };
}

export const ErrorResponse: MessageFns<ErrorResponse> = {
  encode(message: ErrorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ErrorResponse>): ErrorResponse {
    return ErrorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ErrorResponse>): ErrorResponse {
    const message = createBaseErrorResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseResponse(): Response {
  return { error: undefined, setLayerBindings: undefined, getAllLayerBindings: undefined, getSensors: undefined };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(10).fork()).join();
    }
    if (message.setLayerBindings !== undefined) {
      SetLayerBindingsResponse.encode(message.setLayerBindings, writer.uint32(18).fork()).join();
    }
    if (message.getAllLayerBindings !== undefined) {
      GetAllLayerBindingsResponse.encode(message.getAllLayerBindings, writer.uint32(26).fork()).join();
    }
    if (message.getSensors !== undefined) {
      GetSensorsResponse.encode(message.getSensors, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.setLayerBindings = SetLayerBindingsResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.getAllLayerBindings = GetAllLayerBindingsResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.getSensors = GetSensorsResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Response>): Response {
    return Response.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Response>): Response {
    const message = createBaseResponse();
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    message.setLayerBindings = (object.setLayerBindings !== undefined && object.setLayerBindings !== null)
      ? SetLayerBindingsResponse.fromPartial(object.setLayerBindings)
      : undefined;
    message.getAllLayerBindings = (object.getAllLayerBindings !== undefined && object.getAllLayerBindings !== null)
      ? GetAllLayerBindingsResponse.fromPartial(object.getAllLayerBindings)
      : undefined;
    message.getSensors = (object.getSensors !== undefined && object.getSensors !== null)
      ? GetSensorsResponse.fromPartial(object.getSensors)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
