// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: tokyo2006/cirque/cirque.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "tokyo2006.cirque";

export const DataMode = { DATA_MODE_ABSOLUTE: 0, DATA_MODE_RELATIVE: 1, UNRECOGNIZED: -1 } as const;

export type DataMode = typeof DataMode[keyof typeof DataMode];

export namespace DataMode {
  export type DATA_MODE_ABSOLUTE = typeof DataMode.DATA_MODE_ABSOLUTE;
  export type DATA_MODE_RELATIVE = typeof DataMode.DATA_MODE_RELATIVE;
  export type UNRECOGNIZED = typeof DataMode.UNRECOGNIZED;
}

export const Sensitivity = { SENSITIVITY_1X: 0, SENSITIVITY_2X: 1, UNRECOGNIZED: -1 } as const;

export type Sensitivity = typeof Sensitivity[keyof typeof Sensitivity];

export namespace Sensitivity {
  export type SENSITIVITY_1X = typeof Sensitivity.SENSITIVITY_1X;
  export type SENSITIVITY_2X = typeof Sensitivity.SENSITIVITY_2X;
  export type UNRECOGNIZED = typeof Sensitivity.UNRECOGNIZED;
}

export interface CirqueState {
  dataMode?: DataMode | undefined;
  sensitivity?: Sensitivity | undefined;
  invertX?: boolean | undefined;
  invertY?: boolean | undefined;
  swapXy?: boolean | undefined;
  rotateDegrees?: number | undefined;
  primaryTapEnable?: boolean | undefined;
  secondaryTapEnable?: boolean | undefined;
  auxTapEnable?: boolean | undefined;
  tapMaxMs?: number | undefined;
  tapMaxMovement?: number | undefined;
  tapClickMs?: number | undefined;
  tapDragEnable?: boolean | undefined;
  tapDragTimeoutMs?: number | undefined;
  tapDragMaxMovement?: number | undefined;
  secondaryTapAreaWidth?: number | undefined;
  secondaryTapAreaHeight?: number | undefined;
  auxTapAreaWidth?: number | undefined;
  auxTapAreaHeight?: number | undefined;
  edgeMotionEnable?: boolean | undefined;
  edgeMotionZone?: number | undefined;
  edgeMotionSpeed?: number | undefined;
  edgeMotionIntervalMs?: number | undefined;
  edgeMotionStartMs?: number | undefined;
  rightEdgeScrollEnable?: boolean | undefined;
  topEdgeScrollEnable?: boolean | undefined;
  scrollZone?: number | undefined;
  scrollDivisor?: number | undefined;
  invertScroll?: boolean | undefined;
  relativeMultiplier?: number | undefined;
  relativeDivisor?: number | undefined;
  absoluteRelativeMultiplier?: number | undefined;
  absoluteRelativeDivisor?: number | undefined;
  sleepModeEnable?: boolean | undefined;
  dragScrollEnabled?: boolean | undefined;
  pointerSpeedPosition?: number | undefined;
  scrollSpeedPosition?: number | undefined;
}

export interface GetStateRequest {
}

export interface GetStateResponse {
  state: CirqueState | undefined;
}

export interface SetStateRequest {
  state: CirqueState | undefined;
  persist: boolean;
}

export interface SetStateResponse {
  state: CirqueState | undefined;
  persisted: boolean;
}

export interface ResetRequest {
  factoryDefaults: boolean;
}

export interface ResetResponse {
  state: CirqueState | undefined;
}

export interface Request {
  getState?: GetStateRequest | undefined;
  setState?: SetStateRequest | undefined;
  reset?: ResetRequest | undefined;
}

export interface ErrorResponse {
  message: string;
}

export interface Response {
  error?: ErrorResponse | undefined;
  getState?: GetStateResponse | undefined;
  setState?: SetStateResponse | undefined;
  reset?: ResetResponse | undefined;
}

function createBaseCirqueState(): CirqueState {
  return {
    dataMode: undefined,
    sensitivity: undefined,
    invertX: undefined,
    invertY: undefined,
    swapXy: undefined,
    rotateDegrees: undefined,
    primaryTapEnable: undefined,
    secondaryTapEnable: undefined,
    auxTapEnable: undefined,
    tapMaxMs: undefined,
    tapMaxMovement: undefined,
    tapClickMs: undefined,
    tapDragEnable: undefined,
    tapDragTimeoutMs: undefined,
    tapDragMaxMovement: undefined,
    secondaryTapAreaWidth: undefined,
    secondaryTapAreaHeight: undefined,
    auxTapAreaWidth: undefined,
    auxTapAreaHeight: undefined,
    edgeMotionEnable: undefined,
    edgeMotionZone: undefined,
    edgeMotionSpeed: undefined,
    edgeMotionIntervalMs: undefined,
    edgeMotionStartMs: undefined,
    rightEdgeScrollEnable: undefined,
    topEdgeScrollEnable: undefined,
    scrollZone: undefined,
    scrollDivisor: undefined,
    invertScroll: undefined,
    relativeMultiplier: undefined,
    relativeDivisor: undefined,
    absoluteRelativeMultiplier: undefined,
    absoluteRelativeDivisor: undefined,
    sleepModeEnable: undefined,
    dragScrollEnabled: undefined,
    pointerSpeedPosition: undefined,
    scrollSpeedPosition: undefined,
  };
}

export const CirqueState: MessageFns<CirqueState> = {
  encode(message: CirqueState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.dataMode !== undefined) {
      writer.uint32(8).int32(message.dataMode);
    }
    if (message.sensitivity !== undefined) {
      writer.uint32(16).int32(message.sensitivity);
    }
    if (message.invertX !== undefined) {
      writer.uint32(24).bool(message.invertX);
    }
    if (message.invertY !== undefined) {
      writer.uint32(32).bool(message.invertY);
    }
    if (message.swapXy !== undefined) {
      writer.uint32(40).bool(message.swapXy);
    }
    if (message.rotateDegrees !== undefined) {
      writer.uint32(48).uint32(message.rotateDegrees);
    }
    if (message.primaryTapEnable !== undefined) {
      writer.uint32(80).bool(message.primaryTapEnable);
    }
    if (message.secondaryTapEnable !== undefined) {
      writer.uint32(88).bool(message.secondaryTapEnable);
    }
    if (message.auxTapEnable !== undefined) {
      writer.uint32(96).bool(message.auxTapEnable);
    }
    if (message.tapMaxMs !== undefined) {
      writer.uint32(104).uint32(message.tapMaxMs);
    }
    if (message.tapMaxMovement !== undefined) {
      writer.uint32(112).uint32(message.tapMaxMovement);
    }
    if (message.tapClickMs !== undefined) {
      writer.uint32(120).uint32(message.tapClickMs);
    }
    if (message.tapDragEnable !== undefined) {
      writer.uint32(128).bool(message.tapDragEnable);
    }
    if (message.tapDragTimeoutMs !== undefined) {
      writer.uint32(136).uint32(message.tapDragTimeoutMs);
    }
    if (message.tapDragMaxMovement !== undefined) {
      writer.uint32(144).uint32(message.tapDragMaxMovement);
    }
    if (message.secondaryTapAreaWidth !== undefined) {
      writer.uint32(152).uint32(message.secondaryTapAreaWidth);
    }
    if (message.secondaryTapAreaHeight !== undefined) {
      writer.uint32(160).uint32(message.secondaryTapAreaHeight);
    }
    if (message.auxTapAreaWidth !== undefined) {
      writer.uint32(168).uint32(message.auxTapAreaWidth);
    }
    if (message.auxTapAreaHeight !== undefined) {
      writer.uint32(176).uint32(message.auxTapAreaHeight);
    }
    if (message.edgeMotionEnable !== undefined) {
      writer.uint32(240).bool(message.edgeMotionEnable);
    }
    if (message.edgeMotionZone !== undefined) {
      writer.uint32(248).uint32(message.edgeMotionZone);
    }
    if (message.edgeMotionSpeed !== undefined) {
      writer.uint32(256).uint32(message.edgeMotionSpeed);
    }
    if (message.edgeMotionIntervalMs !== undefined) {
      writer.uint32(264).uint32(message.edgeMotionIntervalMs);
    }
    if (message.edgeMotionStartMs !== undefined) {
      writer.uint32(272).uint32(message.edgeMotionStartMs);
    }
    if (message.rightEdgeScrollEnable !== undefined) {
      writer.uint32(320).bool(message.rightEdgeScrollEnable);
    }
    if (message.topEdgeScrollEnable !== undefined) {
      writer.uint32(328).bool(message.topEdgeScrollEnable);
    }
    if (message.scrollZone !== undefined) {
      writer.uint32(336).uint32(message.scrollZone);
    }
    if (message.scrollDivisor !== undefined) {
      writer.uint32(344).uint32(message.scrollDivisor);
    }
    if (message.invertScroll !== undefined) {
      writer.uint32(352).bool(message.invertScroll);
    }
    if (message.relativeMultiplier !== undefined) {
      writer.uint32(400).uint32(message.relativeMultiplier);
    }
    if (message.relativeDivisor !== undefined) {
      writer.uint32(408).uint32(message.relativeDivisor);
    }
    if (message.absoluteRelativeMultiplier !== undefined) {
      writer.uint32(416).uint32(message.absoluteRelativeMultiplier);
    }
    if (message.absoluteRelativeDivisor !== undefined) {
      writer.uint32(424).uint32(message.absoluteRelativeDivisor);
    }
    if (message.sleepModeEnable !== undefined) {
      writer.uint32(480).bool(message.sleepModeEnable);
    }
    if (message.dragScrollEnabled !== undefined) {
      writer.uint32(640).bool(message.dragScrollEnabled);
    }
    if (message.pointerSpeedPosition !== undefined) {
      writer.uint32(720).uint32(message.pointerSpeedPosition);
    }
    if (message.scrollSpeedPosition !== undefined) {
      writer.uint32(728).uint32(message.scrollSpeedPosition);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CirqueState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCirqueState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.dataMode = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sensitivity = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.invertX = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.invertY = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.swapXy = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.rotateDegrees = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.primaryTapEnable = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.secondaryTapEnable = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.auxTapEnable = reader.bool();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.tapMaxMs = reader.uint32();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.tapMaxMovement = reader.uint32();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.tapClickMs = reader.uint32();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.tapDragEnable = reader.bool();
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.tapDragTimeoutMs = reader.uint32();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.tapDragMaxMovement = reader.uint32();
          continue;
        }
        case 19: {
          if (tag !== 152) {
            break;
          }

          message.secondaryTapAreaWidth = reader.uint32();
          continue;
        }
        case 20: {
          if (tag !== 160) {
            break;
          }

          message.secondaryTapAreaHeight = reader.uint32();
          continue;
        }
        case 21: {
          if (tag !== 168) {
            break;
          }

          message.auxTapAreaWidth = reader.uint32();
          continue;
        }
        case 22: {
          if (tag !== 176) {
            break;
          }

          message.auxTapAreaHeight = reader.uint32();
          continue;
        }
        case 30: {
          if (tag !== 240) {
            break;
          }

          message.edgeMotionEnable = reader.bool();
          continue;
        }
        case 31: {
          if (tag !== 248) {
            break;
          }

          message.edgeMotionZone = reader.uint32();
          continue;
        }
        case 32: {
          if (tag !== 256) {
            break;
          }

          message.edgeMotionSpeed = reader.uint32();
          continue;
        }
        case 33: {
          if (tag !== 264) {
            break;
          }

          message.edgeMotionIntervalMs = reader.uint32();
          continue;
        }
        case 34: {
          if (tag !== 272) {
            break;
          }

          message.edgeMotionStartMs = reader.uint32();
          continue;
        }
        case 40: {
          if (tag !== 320) {
            break;
          }

          message.rightEdgeScrollEnable = reader.bool();
          continue;
        }
        case 41: {
          if (tag !== 328) {
            break;
          }

          message.topEdgeScrollEnable = reader.bool();
          continue;
        }
        case 42: {
          if (tag !== 336) {
            break;
          }

          message.scrollZone = reader.uint32();
          continue;
        }
        case 43: {
          if (tag !== 344) {
            break;
          }

          message.scrollDivisor = reader.uint32();
          continue;
        }
        case 44: {
          if (tag !== 352) {
            break;
          }

          message.invertScroll = reader.bool();
          continue;
        }
        case 50: {
          if (tag !== 400) {
            break;
          }

          message.relativeMultiplier = reader.uint32();
          continue;
        }
        case 51: {
          if (tag !== 408) {
            break;
          }

          message.relativeDivisor = reader.uint32();
          continue;
        }
        case 52: {
          if (tag !== 416) {
            break;
          }

          message.absoluteRelativeMultiplier = reader.uint32();
          continue;
        }
        case 53: {
          if (tag !== 424) {
            break;
          }

          message.absoluteRelativeDivisor = reader.uint32();
          continue;
        }
        case 60: {
          if (tag !== 480) {
            break;
          }

          message.sleepModeEnable = reader.bool();
          continue;
        }
        case 80: {
          if (tag !== 640) {
            break;
          }

          message.dragScrollEnabled = reader.bool();
          continue;
        }
        case 90: {
          if (tag !== 720) {
            break;
          }

          message.pointerSpeedPosition = reader.uint32();
          continue;
        }
        case 91: {
          if (tag !== 728) {
            break;
          }

          message.scrollSpeedPosition = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CirqueState>): CirqueState {
    return CirqueState.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CirqueState>): CirqueState {
    const message = createBaseCirqueState();
    message.dataMode = object.dataMode ?? undefined;
    message.sensitivity = object.sensitivity ?? undefined;
    message.invertX = object.invertX ?? undefined;
    message.invertY = object.invertY ?? undefined;
    message.swapXy = object.swapXy ?? undefined;
    message.rotateDegrees = object.rotateDegrees ?? undefined;
    message.primaryTapEnable = object.primaryTapEnable ?? undefined;
    message.secondaryTapEnable = object.secondaryTapEnable ?? undefined;
    message.auxTapEnable = object.auxTapEnable ?? undefined;
    message.tapMaxMs = object.tapMaxMs ?? undefined;
    message.tapMaxMovement = object.tapMaxMovement ?? undefined;
    message.tapClickMs = object.tapClickMs ?? undefined;
    message.tapDragEnable = object.tapDragEnable ?? undefined;
    message.tapDragTimeoutMs = object.tapDragTimeoutMs ?? undefined;
    message.tapDragMaxMovement = object.tapDragMaxMovement ?? undefined;
    message.secondaryTapAreaWidth = object.secondaryTapAreaWidth ?? undefined;
    message.secondaryTapAreaHeight = object.secondaryTapAreaHeight ?? undefined;
    message.auxTapAreaWidth = object.auxTapAreaWidth ?? undefined;
    message.auxTapAreaHeight = object.auxTapAreaHeight ?? undefined;
    message.edgeMotionEnable = object.edgeMotionEnable ?? undefined;
    message.edgeMotionZone = object.edgeMotionZone ?? undefined;
    message.edgeMotionSpeed = object.edgeMotionSpeed ?? undefined;
    message.edgeMotionIntervalMs = object.edgeMotionIntervalMs ?? undefined;
    message.edgeMotionStartMs = object.edgeMotionStartMs ?? undefined;
    message.rightEdgeScrollEnable = object.rightEdgeScrollEnable ?? undefined;
    message.topEdgeScrollEnable = object.topEdgeScrollEnable ?? undefined;
    message.scrollZone = object.scrollZone ?? undefined;
    message.scrollDivisor = object.scrollDivisor ?? undefined;
    message.invertScroll = object.invertScroll ?? undefined;
    message.relativeMultiplier = object.relativeMultiplier ?? undefined;
    message.relativeDivisor = object.relativeDivisor ?? undefined;
    message.absoluteRelativeMultiplier = object.absoluteRelativeMultiplier ?? undefined;
    message.absoluteRelativeDivisor = object.absoluteRelativeDivisor ?? undefined;
    message.sleepModeEnable = object.sleepModeEnable ?? undefined;
    message.dragScrollEnabled = object.dragScrollEnabled ?? undefined;
    message.pointerSpeedPosition = object.pointerSpeedPosition ?? undefined;
    message.scrollSpeedPosition = object.scrollSpeedPosition ?? undefined;
    return message;
  },
};

function createBaseGetStateRequest(): GetStateRequest {
  return {};
}

export const GetStateRequest: MessageFns<GetStateRequest> = {
  encode(_: GetStateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetStateRequest>): GetStateRequest {
    return GetStateRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<GetStateRequest>): GetStateRequest {
    const message = createBaseGetStateRequest();
    return message;
  },
};

function createBaseGetStateResponse(): GetStateResponse {
  return { state: undefined };
}

export const GetStateResponse: MessageFns<GetStateResponse> = {
  encode(message: GetStateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.state !== undefined) {
      CirqueState.encode(message.state, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.state = CirqueState.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetStateResponse>): GetStateResponse {
    return GetStateResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetStateResponse>): GetStateResponse {
    const message = createBaseGetStateResponse();
    message.state = (object.state !== undefined && object.state !== null)
      ? CirqueState.fromPartial(object.state)
      : undefined;
    return message;
  },
};

function createBaseSetStateRequest(): SetStateRequest {
  return { state: undefined, persist: false };
}

export const SetStateRequest: MessageFns<SetStateRequest> = {
  encode(message: SetStateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.state !== undefined) {
      CirqueState.encode(message.state, writer.uint32(10).fork()).join();
    }
    if (message.persist !== false) {
      writer.uint32(16).bool(message.persist);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetStateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetStateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.state = CirqueState.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.persist = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetStateRequest>): SetStateRequest {
    return SetStateRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetStateRequest>): SetStateRequest {
    const message = createBaseSetStateRequest();
    message.state = (object.state !== undefined && object.state !== null)
      ? CirqueState.fromPartial(object.state)
      : undefined;
    message.persist = object.persist ?? false;
    return message;
  },
};

function createBaseSetStateResponse(): SetStateResponse {
  return { state: undefined, persisted: false };
}

export const SetStateResponse: MessageFns<SetStateResponse> = {
  encode(message: SetStateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.state !== undefined) {
      CirqueState.encode(message.state, writer.uint32(10).fork()).join();
    }
    if (message.persisted !== false) {
      writer.uint32(16).bool(message.persisted);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetStateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetStateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.state = CirqueState.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.persisted = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetStateResponse>): SetStateResponse {
    return SetStateResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetStateResponse>): SetStateResponse {
    const message = createBaseSetStateResponse();
    message.state = (object.state !== undefined && object.state !== null)
      ? CirqueState.fromPartial(object.state)
      : undefined;
    message.persisted = object.persisted ?? false;
    return message;
  },
};

function createBaseResetRequest(): ResetRequest {
  return { factoryDefaults: false };
}

export const ResetRequest: MessageFns<ResetRequest> = {
  encode(message: ResetRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.factoryDefaults !== false) {
      writer.uint32(8).bool(message.factoryDefaults);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResetRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResetRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.factoryDefaults = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ResetRequest>): ResetRequest {
    return ResetRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ResetRequest>): ResetRequest {
    const message = createBaseResetRequest();
    message.factoryDefaults = object.factoryDefaults ?? false;
    return message;
  },
};

function createBaseResetResponse(): ResetResponse {
  return { state: undefined };
}

export const ResetResponse: MessageFns<ResetResponse> = {
  encode(message: ResetResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.state !== undefined) {
      CirqueState.encode(message.state, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResetResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResetResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.state = CirqueState.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ResetResponse>): ResetResponse {
    return ResetResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ResetResponse>): ResetResponse {
    const message = createBaseResetResponse();
    message.state = (object.state !== undefined && object.state !== null)
      ? CirqueState.fromPartial(object.state)
      : undefined;
    return message;
  },
};

function createBaseRequest(): Request {
  return { getState: undefined, setState: undefined, reset: undefined };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.getState !== undefined) {
      GetStateRequest.encode(message.getState, writer.uint32(10).fork()).join();
    }
    if (message.setState !== undefined) {
      SetStateRequest.encode(message.setState, writer.uint32(18).fork()).join();
    }
    if (message.reset !== undefined) {
      ResetRequest.encode(message.reset, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.getState = GetStateRequest.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.setState = SetStateRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.reset = ResetRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Request>): Request {
    return Request.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Request>): Request {
    const message = createBaseRequest();
    message.getState = (object.getState !== undefined && object.getState !== null)
      ? GetStateRequest.fromPartial(object.getState)
      : undefined;
    message.setState = (object.setState !== undefined && object.setState !== null)
      ? SetStateRequest.fromPartial(object.setState)
      : undefined;
    message.reset = (object.reset !== undefined && object.reset !== null)
      ? ResetRequest.fromPartial(object.reset)
      : undefined;
    return message;
  },
};

function createBaseErrorResponse(): ErrorResponse {
  return { message: "" };
}

export const ErrorResponse: MessageFns<ErrorResponse> = {
  encode(message: ErrorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ErrorResponse>): ErrorResponse {
    return ErrorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ErrorResponse>): ErrorResponse {
    const message = createBaseErrorResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseResponse(): Response {
  return { error: undefined, getState: undefined, setState: undefined, reset: undefined };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(10).fork()).join();
    }
    if (message.getState !== undefined) {
      GetStateResponse.encode(message.getState, writer.uint32(18).fork()).join();
    }
    if (message.setState !== undefined) {
      SetStateResponse.encode(message.setState, writer.uint32(26).fork()).join();
    }
    if (message.reset !== undefined) {
      ResetResponse.encode(message.reset, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.getState = GetStateResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.setState = SetStateResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.reset = ResetResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Response>): Response {
    return Response.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Response>): Response {
    const message = createBaseResponse();
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    message.getState = (object.getState !== undefined && object.getState !== null)
      ? GetStateResponse.fromPartial(object.getState)
      : undefined;
    message.setState = (object.setState !== undefined && object.setState !== null)
      ? SetStateResponse.fromPartial(object.setState)
      : undefined;
    message.reset = (object.reset !== undefined && object.reset !== null)
      ? ResetResponse.fromPartial(object.reset)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
