// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: zmk/device_info/device_info.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "zmk.device_info";

export interface GetDeviceInfoRequest {
}

export interface BuildInfo {
  zmkVersion: string;
  zmkDirty: boolean;
  zmkConfigVersion: string;
  zmkConfigDirty: boolean;
  moduleVersion: string;
  moduleDirty: boolean;
  zephyrVersion: string;
  buildTimestamp: string;
  board: string;
}

export interface HardwareInfo {
  deviceId: string;
  resetCause: number;
  flashSizeKb: number;
  sramSizeKb: number;
}

export interface ZephyrDevice {
  name: string;
  ready: boolean;
}

export interface ZmkConfig {
  kscanCompatible: string;
  bleEnabled: boolean;
  bleProfileCount: number;
  usbEnabled: boolean;
  splitEnabled: boolean;
  splitRole: string;
  displayEnabled: boolean;
  rgbUnderglowEnabled: boolean;
  backlightEnabled: boolean;
  batteryLevelEnabled: boolean;
}

export interface RuntimeStatus {
  uptimeMs: number;
}

export interface DeviceInfoResponse {
  build: BuildInfo | undefined;
  hardware: HardwareInfo | undefined;
  zephyrDevices: ZephyrDevice[];
  zmkConfig: ZmkConfig | undefined;
  runtime: RuntimeStatus | undefined;
}

export interface ErrorResponse {
  message: string;
}

export interface Request {
  getDeviceInfo?: GetDeviceInfoRequest | undefined;
}

export interface Response {
  error?: ErrorResponse | undefined;
  deviceInfo?: DeviceInfoResponse | undefined;
}

function createBaseGetDeviceInfoRequest(): GetDeviceInfoRequest {
  return {};
}

export const GetDeviceInfoRequest: MessageFns<GetDeviceInfoRequest> = {
  encode(_: GetDeviceInfoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetDeviceInfoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetDeviceInfoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetDeviceInfoRequest>): GetDeviceInfoRequest {
    return GetDeviceInfoRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<GetDeviceInfoRequest>): GetDeviceInfoRequest {
    const message = createBaseGetDeviceInfoRequest();
    return message;
  },
};

function createBaseBuildInfo(): BuildInfo {
  return {
    zmkVersion: "",
    zmkDirty: false,
    zmkConfigVersion: "",
    zmkConfigDirty: false,
    moduleVersion: "",
    moduleDirty: false,
    zephyrVersion: "",
    buildTimestamp: "",
    board: "",
  };
}

export const BuildInfo: MessageFns<BuildInfo> = {
  encode(message: BuildInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.zmkVersion !== "") {
      writer.uint32(10).string(message.zmkVersion);
    }
    if (message.zmkDirty !== false) {
      writer.uint32(16).bool(message.zmkDirty);
    }
    if (message.zmkConfigVersion !== "") {
      writer.uint32(26).string(message.zmkConfigVersion);
    }
    if (message.zmkConfigDirty !== false) {
      writer.uint32(32).bool(message.zmkConfigDirty);
    }
    if (message.moduleVersion !== "") {
      writer.uint32(42).string(message.moduleVersion);
    }
    if (message.moduleDirty !== false) {
      writer.uint32(48).bool(message.moduleDirty);
    }
    if (message.zephyrVersion !== "") {
      writer.uint32(58).string(message.zephyrVersion);
    }
    if (message.buildTimestamp !== "") {
      writer.uint32(66).string(message.buildTimestamp);
    }
    if (message.board !== "") {
      writer.uint32(74).string(message.board);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BuildInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBuildInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.zmkVersion = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.zmkDirty = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.zmkConfigVersion = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.zmkConfigDirty = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.moduleVersion = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.moduleDirty = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.zephyrVersion = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.buildTimestamp = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.board = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<BuildInfo>): BuildInfo {
    return BuildInfo.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BuildInfo>): BuildInfo {
    const message = createBaseBuildInfo();
    message.zmkVersion = object.zmkVersion ?? "";
    message.zmkDirty = object.zmkDirty ?? false;
    message.zmkConfigVersion = object.zmkConfigVersion ?? "";
    message.zmkConfigDirty = object.zmkConfigDirty ?? false;
    message.moduleVersion = object.moduleVersion ?? "";
    message.moduleDirty = object.moduleDirty ?? false;
    message.zephyrVersion = object.zephyrVersion ?? "";
    message.buildTimestamp = object.buildTimestamp ?? "";
    message.board = object.board ?? "";
    return message;
  },
};

function createBaseHardwareInfo(): HardwareInfo {
  return { deviceId: "", resetCause: 0, flashSizeKb: 0, sramSizeKb: 0 };
}

export const HardwareInfo: MessageFns<HardwareInfo> = {
  encode(message: HardwareInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deviceId !== "") {
      writer.uint32(10).string(message.deviceId);
    }
    if (message.resetCause !== 0) {
      writer.uint32(16).uint32(message.resetCause);
    }
    if (message.flashSizeKb !== 0) {
      writer.uint32(24).uint32(message.flashSizeKb);
    }
    if (message.sramSizeKb !== 0) {
      writer.uint32(32).uint32(message.sramSizeKb);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HardwareInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHardwareInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.deviceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.resetCause = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.flashSizeKb = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.sramSizeKb = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<HardwareInfo>): HardwareInfo {
    return HardwareInfo.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HardwareInfo>): HardwareInfo {
    const message = createBaseHardwareInfo();
    message.deviceId = object.deviceId ?? "";
    message.resetCause = object.resetCause ?? 0;
    message.flashSizeKb = object.flashSizeKb ?? 0;
    message.sramSizeKb = object.sramSizeKb ?? 0;
    return message;
  },
};

function createBaseZephyrDevice(): ZephyrDevice {
  return { name: "", ready: false };
}

export const ZephyrDevice: MessageFns<ZephyrDevice> = {
  encode(message: ZephyrDevice, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.ready !== false) {
      writer.uint32(16).bool(message.ready);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ZephyrDevice {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseZephyrDevice();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.ready = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ZephyrDevice>): ZephyrDevice {
    return ZephyrDevice.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ZephyrDevice>): ZephyrDevice {
    const message = createBaseZephyrDevice();
    message.name = object.name ?? "";
    message.ready = object.ready ?? false;
    return message;
  },
};

function createBaseZmkConfig(): ZmkConfig {
  return {
    kscanCompatible: "",
    bleEnabled: false,
    bleProfileCount: 0,
    usbEnabled: false,
    splitEnabled: false,
    splitRole: "",
    displayEnabled: false,
    rgbUnderglowEnabled: false,
    backlightEnabled: false,
    batteryLevelEnabled: false,
  };
}

export const ZmkConfig: MessageFns<ZmkConfig> = {
  encode(message: ZmkConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.kscanCompatible !== "") {
      writer.uint32(10).string(message.kscanCompatible);
    }
    if (message.bleEnabled !== false) {
      writer.uint32(16).bool(message.bleEnabled);
    }
    if (message.bleProfileCount !== 0) {
      writer.uint32(24).uint32(message.bleProfileCount);
    }
    if (message.usbEnabled !== false) {
      writer.uint32(32).bool(message.usbEnabled);
    }
    if (message.splitEnabled !== false) {
      writer.uint32(40).bool(message.splitEnabled);
    }
    if (message.splitRole !== "") {
      writer.uint32(50).string(message.splitRole);
    }
    if (message.displayEnabled !== false) {
      writer.uint32(56).bool(message.displayEnabled);
    }
    if (message.rgbUnderglowEnabled !== false) {
      writer.uint32(64).bool(message.rgbUnderglowEnabled);
    }
    if (message.backlightEnabled !== false) {
      writer.uint32(72).bool(message.backlightEnabled);
    }
    if (message.batteryLevelEnabled !== false) {
      writer.uint32(80).bool(message.batteryLevelEnabled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ZmkConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseZmkConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.kscanCompatible = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.bleEnabled = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.bleProfileCount = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.usbEnabled = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.splitEnabled = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.splitRole = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.displayEnabled = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.rgbUnderglowEnabled = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.backlightEnabled = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.batteryLevelEnabled = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ZmkConfig>): ZmkConfig {
    return ZmkConfig.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ZmkConfig>): ZmkConfig {
    const message = createBaseZmkConfig();
    message.kscanCompatible = object.kscanCompatible ?? "";
    message.bleEnabled = object.bleEnabled ?? false;
    message.bleProfileCount = object.bleProfileCount ?? 0;
    message.usbEnabled = object.usbEnabled ?? false;
    message.splitEnabled = object.splitEnabled ?? false;
    message.splitRole = object.splitRole ?? "";
    message.displayEnabled = object.displayEnabled ?? false;
    message.rgbUnderglowEnabled = object.rgbUnderglowEnabled ?? false;
    message.backlightEnabled = object.backlightEnabled ?? false;
    message.batteryLevelEnabled = object.batteryLevelEnabled ?? false;
    return message;
  },
};

function createBaseRuntimeStatus(): RuntimeStatus {
  return { uptimeMs: 0 };
}

export const RuntimeStatus: MessageFns<RuntimeStatus> = {
  encode(message: RuntimeStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uptimeMs !== 0) {
      writer.uint32(8).uint32(message.uptimeMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RuntimeStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRuntimeStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.uptimeMs = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<RuntimeStatus>): RuntimeStatus {
    return RuntimeStatus.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RuntimeStatus>): RuntimeStatus {
    const message = createBaseRuntimeStatus();
    message.uptimeMs = object.uptimeMs ?? 0;
    return message;
  },
};

function createBaseDeviceInfoResponse(): DeviceInfoResponse {
  return { build: undefined, hardware: undefined, zephyrDevices: [], zmkConfig: undefined, runtime: undefined };
}

export const DeviceInfoResponse: MessageFns<DeviceInfoResponse> = {
  encode(message: DeviceInfoResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.build !== undefined) {
      BuildInfo.encode(message.build, writer.uint32(10).fork()).join();
    }
    if (message.hardware !== undefined) {
      HardwareInfo.encode(message.hardware, writer.uint32(18).fork()).join();
    }
    for (const v of message.zephyrDevices) {
      ZephyrDevice.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.zmkConfig !== undefined) {
      ZmkConfig.encode(message.zmkConfig, writer.uint32(34).fork()).join();
    }
    if (message.runtime !== undefined) {
      RuntimeStatus.encode(message.runtime, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeviceInfoResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeviceInfoResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.build = BuildInfo.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.hardware = HardwareInfo.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.zephyrDevices.push(ZephyrDevice.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.zmkConfig = ZmkConfig.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.runtime = RuntimeStatus.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<DeviceInfoResponse>): DeviceInfoResponse {
    return DeviceInfoResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeviceInfoResponse>): DeviceInfoResponse {
    const message = createBaseDeviceInfoResponse();
    message.build = (object.build !== undefined && object.build !== null)
      ? BuildInfo.fromPartial(object.build)
      : undefined;
    message.hardware = (object.hardware !== undefined && object.hardware !== null)
      ? HardwareInfo.fromPartial(object.hardware)
      : undefined;
    message.zephyrDevices = object.zephyrDevices?.map((e) => ZephyrDevice.fromPartial(e)) || [];
    message.zmkConfig = (object.zmkConfig !== undefined && object.zmkConfig !== null)
      ? ZmkConfig.fromPartial(object.zmkConfig)
      : undefined;
    message.runtime = (object.runtime !== undefined && object.runtime !== null)
      ? RuntimeStatus.fromPartial(object.runtime)
      : undefined;
    return message;
  },
};

function createBaseErrorResponse(): ErrorResponse {
  return { message: "" };
}

export const ErrorResponse: MessageFns<ErrorResponse> = {
  encode(message: ErrorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ErrorResponse>): ErrorResponse {
    return ErrorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ErrorResponse>): ErrorResponse {
    const message = createBaseErrorResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseRequest(): Request {
  return { getDeviceInfo: undefined };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.getDeviceInfo !== undefined) {
      GetDeviceInfoRequest.encode(message.getDeviceInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.getDeviceInfo = GetDeviceInfoRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Request>): Request {
    return Request.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Request>): Request {
    const message = createBaseRequest();
    message.getDeviceInfo = (object.getDeviceInfo !== undefined && object.getDeviceInfo !== null)
      ? GetDeviceInfoRequest.fromPartial(object.getDeviceInfo)
      : undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return { error: undefined, deviceInfo: undefined };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(10).fork()).join();
    }
    if (message.deviceInfo !== undefined) {
      DeviceInfoResponse.encode(message.deviceInfo, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.deviceInfo = DeviceInfoResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Response>): Response {
    return Response.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Response>): Response {
    const message = createBaseResponse();
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    message.deviceInfo = (object.deviceInfo !== undefined && object.deviceInfo !== null)
      ? DeviceInfoResponse.fromPartial(object.deviceInfo)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
