// Vendored copy of the `zmk-feature-fast-keymap` package
// (cormoran/zmk-feature-fast-keymap, web/packages/fast-keymap) -- a
// transport-free client for the `cormoran__fast_keymap` custom ZMK Studio RPC
// subsystem. Consumers supply their own `call(request): Promise<Response |
// null>` (see `FastKeymapCall`) -- this owns the RPC-data-handling, caching,
// and fingerprint-canonicalization logic only, not the transport.
//
// Vendored (rather than depended on via npm) to match how this repo vendors
// every other custom-subsystem proto/client, and so the proto is generated by
// this repo's own `buf generate` pipeline (src/proto/...). Keep in sync with
// upstream; only the proto import paths were changed.

export {
  loadFastKeymap,
  loadPhysicalLayoutGeometry,
  indexBehaviorsById,
  formatBindingToken,
  exportKeymapText,
  FastKeymapCacheKeys,
  type FastKeymapCall,
  type FastKeymapBinding,
  type BehaviorResolvedFrom,
  type FastKeymapBehavior,
  type FastKeymapLayer,
  type FastKeymapLayoutKey,
  type FastKeymapLayout,
  type FastKeymapLoadStats,
  type FastKeymapModel,
  type LoadFastKeymapOptions,
} from "./fastKeymap";

export {
  FK_DEFINITION_VERSION,
  STANDARD_BEHAVIORS,
  bundledByDefFp,
  type StandardBehaviorDef,
} from "./standardBehaviors";

export { crc32Update, crcStrU16len, defFp } from "./fingerprint";

export {
  Request,
  Response,
  ErrorCode,
  BehaviorDetailsMode,
  LayoutDetailsMode,
} from "../../proto/cormoran/fast_keymap/fast_keymap";
