// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: cormoran/watchdog/watchdog.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cormoran.watchdog";

/**
 * Incident kind discriminator, mirrors enum zmk_watchdog_incident_type in
 * include/cormoran/zmk/watchdog.h.
 */
export const IncidentType = { FREEZE: 0, FATAL: 1, RESET_CAUSE: 2, UNRECOGNIZED: -1 } as const;

export type IncidentType = typeof IncidentType[keyof typeof IncidentType];

export namespace IncidentType {
  export type FREEZE = typeof IncidentType.FREEZE;
  export type FATAL = typeof IncidentType.FATAL;
  export type RESET_CAUSE = typeof IncidentType.RESET_CAUSE;
  export type UNRECOGNIZED = typeof IncidentType.UNRECOGNIZED;
}

/** Mirrors struct zmk_watchdog_incident_freeze_detail. */
export interface FreezeDetail {
  channelId: number;
  queueName: string;
}

/** Mirrors struct zmk_watchdog_incident_fatal_detail. */
export interface FatalDetail {
  reason: number;
  pc: number;
  lr: number;
  threadName: string;
}

/** Mirrors struct zmk_watchdog_incident_reset_detail. */
export interface ResetDetail {
  causeBits: number;
}

/**
 * A single incident, sourced either locally (source == 0, this device) or
 * relayed from a split peripheral (source == peripheral slot + 1, see
 * DESIGN.md SS7).
 */
export interface Incident {
  id: number;
  source: number;
  type: IncidentType;
  bootOrdinal: number;
  uptimeS: number;
  freeze?: FreezeDetail | undefined;
  fatal?: FatalDetail | undefined;
  reset?: ResetDetail | undefined;
}

/**
 * Request current status (capacity/stored/dropped/recording_stopped).
 * `source` selects which half answers: 0 = local/central (answered
 * synchronously); N>0 = split peripheral slot N, relayed over
 * CONFIG_ZMK_SPLIT_RELAY_EVENT (see DESIGN.md SS7) -- the reply arrives as a
 * PeripheralResponse Notification instead of a synchronous Response.
 */
export interface GetStatusRequest {
  source: number;
}

/**
 * Paginated incident listing. start_index is 0-based over the store's
 * dense enumeration order (see zmk_watchdog_store_get()). `source`: see
 * GetStatusRequest.source.
 */
export interface ListIncidentsRequest {
  startIndex: number;
  source: number;
}

/**
 * Delete specific incidents by id, or every incident when all=true (ids is
 * ignored in that case). `source`: see GetStatusRequest.source.
 */
export interface DeleteIncidentsRequest {
  ids: number[];
  all: boolean;
  source: number;
}

export interface Request {
  getStatus?: GetStatusRequest | undefined;
  listIncidents?: ListIncidentsRequest | undefined;
  deleteIncidents?: DeleteIncidentsRequest | undefined;
}

export interface ErrorResponse {
  message: string;
}

/**
 * Mirrors the store's capacity/count/dropped/recording_stopped accessors
 * (include/cormoran/zmk/watchdog.h).
 */
export interface StatusResponse {
  capacity: number;
  stored: number;
  droppedSinceBoot: number;
  recordingStopped: boolean;
}

/**
 * At most 4 incidents per page -- see the BUILD_ASSERT in
 * src/studio/watchdog_handler.c for the size arithmetic against
 * CONFIG_ZMK_STUDIO_RPC_TX_BUF_SIZE.
 */
export interface IncidentPageResponse {
  incidents: Incident[];
  total: number;
  startIndex: number;
}

export interface DeleteResultResponse {
  deleted: number;
}

/**
 * Returned immediately in place of the real response when a request's
 * `source` targets a split peripheral (relaying over
 * CONFIG_ZMK_SPLIT_RELAY_EVENT is inherently asynchronous -- it cannot fit
 * the Studio RPC call/response model). The real Response for this
 * `request_id` arrives later as a PeripheralResponse Notification. See
 * DESIGN.md SS7.
 */
export interface DeferredResponse {
  requestId: number;
}

export interface Response {
  error?: ErrorResponse | undefined;
  status?: StatusResponse | undefined;
  incidentPage?: IncidentPageResponse | undefined;
  deleteResult?: DeleteResultResponse | undefined;
  deferred?: DeferredResponse | undefined;
}

/**
 * Pushed unsolicited (raise_zmk_studio_custom_notification) when a new
 * incident is persisted, so the web UI can show it live without polling.
 * See DESIGN.md SS8.
 */
export interface IncidentRecordedNotification {
  incident: Incident | undefined;
}

/**
 * The real response to a request that returned a DeferredResponse, once the
 * targeted peripheral's answer has relayed back to the central. Matches
 * pmw3610's PeripheralResponse pattern (src/split/watchdog_relay.c).
 */
export interface PeripheralResponse {
  /**
   * Matches the source given in the original request (1 = first
   * peripheral, etc; never 0 -- local requests are answered synchronously
   * and never produce a DeferredResponse/PeripheralResponse).
   */
  source: number;
  requestId: number;
  response: Response | undefined;
}

export interface Notification {
  incidentRecorded?: IncidentRecordedNotification | undefined;
  peripheralResponse?: PeripheralResponse | undefined;
}

/**
 * Wire format for relaying a Request to a split peripheral and its Response
 * back, carried as the opaque payload of this module's own
 * zmk_watchdog_relay_request/zmk_watchdog_relay_response ZMK split relay
 * events (see src/split/watchdog_relay.c) -- NOT part of the Request/Response
 * oneofs above, and never sent directly over the Studio RPC transport.
 */
export interface RelayRequest {
  requestId: number;
  request: Request | undefined;
}

export interface RelayResponse {
  requestId: number;
  response: Response | undefined;
}

function createBaseFreezeDetail(): FreezeDetail {
  return { channelId: 0, queueName: "" };
}

export const FreezeDetail: MessageFns<FreezeDetail> = {
  encode(message: FreezeDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.channelId !== 0) {
      writer.uint32(8).uint32(message.channelId);
    }
    if (message.queueName !== "") {
      writer.uint32(18).string(message.queueName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FreezeDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFreezeDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.channelId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.queueName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FreezeDetail>): FreezeDetail {
    return FreezeDetail.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FreezeDetail>): FreezeDetail {
    const message = createBaseFreezeDetail();
    message.channelId = object.channelId ?? 0;
    message.queueName = object.queueName ?? "";
    return message;
  },
};

function createBaseFatalDetail(): FatalDetail {
  return { reason: 0, pc: 0, lr: 0, threadName: "" };
}

export const FatalDetail: MessageFns<FatalDetail> = {
  encode(message: FatalDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reason !== 0) {
      writer.uint32(8).uint32(message.reason);
    }
    if (message.pc !== 0) {
      writer.uint32(16).uint32(message.pc);
    }
    if (message.lr !== 0) {
      writer.uint32(24).uint32(message.lr);
    }
    if (message.threadName !== "") {
      writer.uint32(34).string(message.threadName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FatalDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFatalDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.reason = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pc = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.lr = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.threadName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FatalDetail>): FatalDetail {
    return FatalDetail.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FatalDetail>): FatalDetail {
    const message = createBaseFatalDetail();
    message.reason = object.reason ?? 0;
    message.pc = object.pc ?? 0;
    message.lr = object.lr ?? 0;
    message.threadName = object.threadName ?? "";
    return message;
  },
};

function createBaseResetDetail(): ResetDetail {
  return { causeBits: 0 };
}

export const ResetDetail: MessageFns<ResetDetail> = {
  encode(message: ResetDetail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.causeBits !== 0) {
      writer.uint32(8).uint32(message.causeBits);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResetDetail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResetDetail();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.causeBits = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ResetDetail>): ResetDetail {
    return ResetDetail.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ResetDetail>): ResetDetail {
    const message = createBaseResetDetail();
    message.causeBits = object.causeBits ?? 0;
    return message;
  },
};

function createBaseIncident(): Incident {
  return {
    id: 0,
    source: 0,
    type: 0,
    bootOrdinal: 0,
    uptimeS: 0,
    freeze: undefined,
    fatal: undefined,
    reset: undefined,
  };
}

export const Incident: MessageFns<Incident> = {
  encode(message: Incident, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    if (message.source !== 0) {
      writer.uint32(16).uint32(message.source);
    }
    if (message.type !== 0) {
      writer.uint32(24).int32(message.type);
    }
    if (message.bootOrdinal !== 0) {
      writer.uint32(32).uint32(message.bootOrdinal);
    }
    if (message.uptimeS !== 0) {
      writer.uint32(40).uint32(message.uptimeS);
    }
    if (message.freeze !== undefined) {
      FreezeDetail.encode(message.freeze, writer.uint32(50).fork()).join();
    }
    if (message.fatal !== undefined) {
      FatalDetail.encode(message.fatal, writer.uint32(58).fork()).join();
    }
    if (message.reset !== undefined) {
      ResetDetail.encode(message.reset, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Incident {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIncident();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.source = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.bootOrdinal = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.uptimeS = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.freeze = FreezeDetail.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.fatal = FatalDetail.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.reset = ResetDetail.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Incident>): Incident {
    return Incident.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Incident>): Incident {
    const message = createBaseIncident();
    message.id = object.id ?? 0;
    message.source = object.source ?? 0;
    message.type = object.type ?? 0;
    message.bootOrdinal = object.bootOrdinal ?? 0;
    message.uptimeS = object.uptimeS ?? 0;
    message.freeze = (object.freeze !== undefined && object.freeze !== null)
      ? FreezeDetail.fromPartial(object.freeze)
      : undefined;
    message.fatal = (object.fatal !== undefined && object.fatal !== null)
      ? FatalDetail.fromPartial(object.fatal)
      : undefined;
    message.reset = (object.reset !== undefined && object.reset !== null)
      ? ResetDetail.fromPartial(object.reset)
      : undefined;
    return message;
  },
};

function createBaseGetStatusRequest(): GetStatusRequest {
  return { source: 0 };
}

export const GetStatusRequest: MessageFns<GetStatusRequest> = {
  encode(message: GetStatusRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.source !== 0) {
      writer.uint32(8).uint32(message.source);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStatusRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStatusRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.source = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetStatusRequest>): GetStatusRequest {
    return GetStatusRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetStatusRequest>): GetStatusRequest {
    const message = createBaseGetStatusRequest();
    message.source = object.source ?? 0;
    return message;
  },
};

function createBaseListIncidentsRequest(): ListIncidentsRequest {
  return { startIndex: 0, source: 0 };
}

export const ListIncidentsRequest: MessageFns<ListIncidentsRequest> = {
  encode(message: ListIncidentsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.startIndex !== 0) {
      writer.uint32(8).uint32(message.startIndex);
    }
    if (message.source !== 0) {
      writer.uint32(16).uint32(message.source);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListIncidentsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListIncidentsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.startIndex = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.source = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListIncidentsRequest>): ListIncidentsRequest {
    return ListIncidentsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListIncidentsRequest>): ListIncidentsRequest {
    const message = createBaseListIncidentsRequest();
    message.startIndex = object.startIndex ?? 0;
    message.source = object.source ?? 0;
    return message;
  },
};

function createBaseDeleteIncidentsRequest(): DeleteIncidentsRequest {
  return { ids: [], all: false, source: 0 };
}

export const DeleteIncidentsRequest: MessageFns<DeleteIncidentsRequest> = {
  encode(message: DeleteIncidentsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.ids) {
      writer.uint32(v);
    }
    writer.join();
    if (message.all !== false) {
      writer.uint32(16).bool(message.all);
    }
    if (message.source !== 0) {
      writer.uint32(24).uint32(message.source);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteIncidentsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteIncidentsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.ids.push(reader.uint32());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.ids.push(reader.uint32());
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.all = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.source = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<DeleteIncidentsRequest>): DeleteIncidentsRequest {
    return DeleteIncidentsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeleteIncidentsRequest>): DeleteIncidentsRequest {
    const message = createBaseDeleteIncidentsRequest();
    message.ids = object.ids?.map((e) => e) || [];
    message.all = object.all ?? false;
    message.source = object.source ?? 0;
    return message;
  },
};

function createBaseRequest(): Request {
  return { getStatus: undefined, listIncidents: undefined, deleteIncidents: undefined };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.getStatus !== undefined) {
      GetStatusRequest.encode(message.getStatus, writer.uint32(10).fork()).join();
    }
    if (message.listIncidents !== undefined) {
      ListIncidentsRequest.encode(message.listIncidents, writer.uint32(18).fork()).join();
    }
    if (message.deleteIncidents !== undefined) {
      DeleteIncidentsRequest.encode(message.deleteIncidents, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.getStatus = GetStatusRequest.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.listIncidents = ListIncidentsRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.deleteIncidents = DeleteIncidentsRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Request>): Request {
    return Request.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Request>): Request {
    const message = createBaseRequest();
    message.getStatus = (object.getStatus !== undefined && object.getStatus !== null)
      ? GetStatusRequest.fromPartial(object.getStatus)
      : undefined;
    message.listIncidents = (object.listIncidents !== undefined && object.listIncidents !== null)
      ? ListIncidentsRequest.fromPartial(object.listIncidents)
      : undefined;
    message.deleteIncidents = (object.deleteIncidents !== undefined && object.deleteIncidents !== null)
      ? DeleteIncidentsRequest.fromPartial(object.deleteIncidents)
      : undefined;
    return message;
  },
};

function createBaseErrorResponse(): ErrorResponse {
  return { message: "" };
}

export const ErrorResponse: MessageFns<ErrorResponse> = {
  encode(message: ErrorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ErrorResponse>): ErrorResponse {
    return ErrorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ErrorResponse>): ErrorResponse {
    const message = createBaseErrorResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseStatusResponse(): StatusResponse {
  return { capacity: 0, stored: 0, droppedSinceBoot: 0, recordingStopped: false };
}

export const StatusResponse: MessageFns<StatusResponse> = {
  encode(message: StatusResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.capacity !== 0) {
      writer.uint32(8).uint32(message.capacity);
    }
    if (message.stored !== 0) {
      writer.uint32(16).uint32(message.stored);
    }
    if (message.droppedSinceBoot !== 0) {
      writer.uint32(24).uint32(message.droppedSinceBoot);
    }
    if (message.recordingStopped !== false) {
      writer.uint32(32).bool(message.recordingStopped);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StatusResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatusResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.capacity = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.stored = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.droppedSinceBoot = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.recordingStopped = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<StatusResponse>): StatusResponse {
    return StatusResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StatusResponse>): StatusResponse {
    const message = createBaseStatusResponse();
    message.capacity = object.capacity ?? 0;
    message.stored = object.stored ?? 0;
    message.droppedSinceBoot = object.droppedSinceBoot ?? 0;
    message.recordingStopped = object.recordingStopped ?? false;
    return message;
  },
};

function createBaseIncidentPageResponse(): IncidentPageResponse {
  return { incidents: [], total: 0, startIndex: 0 };
}

export const IncidentPageResponse: MessageFns<IncidentPageResponse> = {
  encode(message: IncidentPageResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.incidents) {
      Incident.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).uint32(message.total);
    }
    if (message.startIndex !== 0) {
      writer.uint32(24).uint32(message.startIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IncidentPageResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIncidentPageResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.incidents.push(Incident.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.startIndex = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<IncidentPageResponse>): IncidentPageResponse {
    return IncidentPageResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<IncidentPageResponse>): IncidentPageResponse {
    const message = createBaseIncidentPageResponse();
    message.incidents = object.incidents?.map((e) => Incident.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    message.startIndex = object.startIndex ?? 0;
    return message;
  },
};

function createBaseDeleteResultResponse(): DeleteResultResponse {
  return { deleted: 0 };
}

export const DeleteResultResponse: MessageFns<DeleteResultResponse> = {
  encode(message: DeleteResultResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deleted !== 0) {
      writer.uint32(8).uint32(message.deleted);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteResultResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteResultResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.deleted = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<DeleteResultResponse>): DeleteResultResponse {
    return DeleteResultResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeleteResultResponse>): DeleteResultResponse {
    const message = createBaseDeleteResultResponse();
    message.deleted = object.deleted ?? 0;
    return message;
  },
};

function createBaseDeferredResponse(): DeferredResponse {
  return { requestId: 0 };
}

export const DeferredResponse: MessageFns<DeferredResponse> = {
  encode(message: DeferredResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== 0) {
      writer.uint32(8).uint32(message.requestId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeferredResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeferredResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.requestId = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<DeferredResponse>): DeferredResponse {
    return DeferredResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeferredResponse>): DeferredResponse {
    const message = createBaseDeferredResponse();
    message.requestId = object.requestId ?? 0;
    return message;
  },
};

function createBaseResponse(): Response {
  return { error: undefined, status: undefined, incidentPage: undefined, deleteResult: undefined, deferred: undefined };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(10).fork()).join();
    }
    if (message.status !== undefined) {
      StatusResponse.encode(message.status, writer.uint32(18).fork()).join();
    }
    if (message.incidentPage !== undefined) {
      IncidentPageResponse.encode(message.incidentPage, writer.uint32(26).fork()).join();
    }
    if (message.deleteResult !== undefined) {
      DeleteResultResponse.encode(message.deleteResult, writer.uint32(34).fork()).join();
    }
    if (message.deferred !== undefined) {
      DeferredResponse.encode(message.deferred, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = StatusResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.incidentPage = IncidentPageResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.deleteResult = DeleteResultResponse.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.deferred = DeferredResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Response>): Response {
    return Response.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Response>): Response {
    const message = createBaseResponse();
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    message.status = (object.status !== undefined && object.status !== null)
      ? StatusResponse.fromPartial(object.status)
      : undefined;
    message.incidentPage = (object.incidentPage !== undefined && object.incidentPage !== null)
      ? IncidentPageResponse.fromPartial(object.incidentPage)
      : undefined;
    message.deleteResult = (object.deleteResult !== undefined && object.deleteResult !== null)
      ? DeleteResultResponse.fromPartial(object.deleteResult)
      : undefined;
    message.deferred = (object.deferred !== undefined && object.deferred !== null)
      ? DeferredResponse.fromPartial(object.deferred)
      : undefined;
    return message;
  },
};

function createBaseIncidentRecordedNotification(): IncidentRecordedNotification {
  return { incident: undefined };
}

export const IncidentRecordedNotification: MessageFns<IncidentRecordedNotification> = {
  encode(message: IncidentRecordedNotification, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.incident !== undefined) {
      Incident.encode(message.incident, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IncidentRecordedNotification {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIncidentRecordedNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.incident = Incident.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<IncidentRecordedNotification>): IncidentRecordedNotification {
    return IncidentRecordedNotification.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<IncidentRecordedNotification>): IncidentRecordedNotification {
    const message = createBaseIncidentRecordedNotification();
    message.incident = (object.incident !== undefined && object.incident !== null)
      ? Incident.fromPartial(object.incident)
      : undefined;
    return message;
  },
};

function createBasePeripheralResponse(): PeripheralResponse {
  return { source: 0, requestId: 0, response: undefined };
}

export const PeripheralResponse: MessageFns<PeripheralResponse> = {
  encode(message: PeripheralResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.source !== 0) {
      writer.uint32(8).uint32(message.source);
    }
    if (message.requestId !== 0) {
      writer.uint32(16).uint32(message.requestId);
    }
    if (message.response !== undefined) {
      Response.encode(message.response, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PeripheralResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePeripheralResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.source = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.requestId = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.response = Response.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<PeripheralResponse>): PeripheralResponse {
    return PeripheralResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PeripheralResponse>): PeripheralResponse {
    const message = createBasePeripheralResponse();
    message.source = object.source ?? 0;
    message.requestId = object.requestId ?? 0;
    message.response = (object.response !== undefined && object.response !== null)
      ? Response.fromPartial(object.response)
      : undefined;
    return message;
  },
};

function createBaseNotification(): Notification {
  return { incidentRecorded: undefined, peripheralResponse: undefined };
}

export const Notification: MessageFns<Notification> = {
  encode(message: Notification, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.incidentRecorded !== undefined) {
      IncidentRecordedNotification.encode(message.incidentRecorded, writer.uint32(10).fork()).join();
    }
    if (message.peripheralResponse !== undefined) {
      PeripheralResponse.encode(message.peripheralResponse, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Notification {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.incidentRecorded = IncidentRecordedNotification.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.peripheralResponse = PeripheralResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Notification>): Notification {
    return Notification.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Notification>): Notification {
    const message = createBaseNotification();
    message.incidentRecorded = (object.incidentRecorded !== undefined && object.incidentRecorded !== null)
      ? IncidentRecordedNotification.fromPartial(object.incidentRecorded)
      : undefined;
    message.peripheralResponse = (object.peripheralResponse !== undefined && object.peripheralResponse !== null)
      ? PeripheralResponse.fromPartial(object.peripheralResponse)
      : undefined;
    return message;
  },
};

function createBaseRelayRequest(): RelayRequest {
  return { requestId: 0, request: undefined };
}

export const RelayRequest: MessageFns<RelayRequest> = {
  encode(message: RelayRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== 0) {
      writer.uint32(8).uint32(message.requestId);
    }
    if (message.request !== undefined) {
      Request.encode(message.request, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RelayRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRelayRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.requestId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.request = Request.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<RelayRequest>): RelayRequest {
    return RelayRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RelayRequest>): RelayRequest {
    const message = createBaseRelayRequest();
    message.requestId = object.requestId ?? 0;
    message.request = (object.request !== undefined && object.request !== null)
      ? Request.fromPartial(object.request)
      : undefined;
    return message;
  },
};

function createBaseRelayResponse(): RelayResponse {
  return { requestId: 0, response: undefined };
}

export const RelayResponse: MessageFns<RelayResponse> = {
  encode(message: RelayResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== 0) {
      writer.uint32(8).uint32(message.requestId);
    }
    if (message.response !== undefined) {
      Response.encode(message.response, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RelayResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRelayResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.requestId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.response = Response.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<RelayResponse>): RelayResponse {
    return RelayResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RelayResponse>): RelayResponse {
    const message = createBaseRelayResponse();
    message.requestId = object.requestId ?? 0;
    message.response = (object.response !== undefined && object.response !== null)
      ? Response.fromPartial(object.response)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
