// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: cormoran/pmw3610/pmw3610.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "cormoran.pmw3610";

export interface GetInfoRequest {
}

export interface RuntimeConfig {
  cpi: number;
  swapXy: boolean;
  invertX: boolean;
  invertY: boolean;
  forceAwake: boolean;
  smartAlgorithm: boolean;
  runDownshiftMs: number;
  rest1DownshiftMs: number;
  rest2DownshiftMs: number;
  rest1SampleMs: number;
  rest2SampleMs: number;
  rest3SampleMs: number;
  reportIntervalMinMs: number;
}

export interface DeviceInfo {
  ready: boolean;
  productId: number;
  revisionId: number;
  initError: number;
  runtimeConfig: RuntimeConfig | undefined;
}

export interface GetInfoResponse {
  devices: DeviceInfo[];
}

export interface ReadDiagnosticsRequest {
  deviceIndex: number;
}

export interface ReadDiagnosticsResponse {
  squal: number;
  shutter: number;
  pixMax: number;
  pixAvg: number;
  pixMin: number;
}

export interface ReadRegisterRequest {
  deviceIndex: number;
  address: number;
}

export interface ReadRegisterResponse {
  value: number;
}

/**
 * Debug/tuning facility: writes an arbitrary sensor register with no
 * validation beyond fitting in a byte. This is the main reason the whole
 * cormoran__pmw3610 subsystem is SECURED (ZMK Studio must be unlocked) --
 * see README.md's "Security" section for caveats before using this over an
 * untrusted transport.
 */
export interface WriteRegisterRequest {
  deviceIndex: number;
  address: number;
  value: number;
}

export interface WriteRegisterResponse {
}

/**
 * Captures a still frame (pixel array) from the sensor into a firmware-side
 * static buffer, following the official PMW3610 datasheet (R2.4) Pixel_Grab
 * procedure: an arm sequence (SPI clock request + page-1 magic enable + test
 * clock on + PIXEL_GRAB arm), then per pixel: wait for OBSERVATION1 (0x2D)
 * bit2, read PIXEL_GRAB (0x35), write OBSERVATION1 = 0x01 to advance.
 * PRBS_TEST_CTL (0x47) bit0 at the end indicates a complete 484-pixel frame.
 * Rejects with an ErrorResponse if a SetFrameStream stream is currently
 * active (they share the same firmware-side buffer/frame_id counter) --
 * call SetFrameStream{enable: false} first.
 */
export interface CaptureFrameRequest {
  deviceIndex: number;
  /**
   * Number of pixels to read. 0 means the driver default (484 = 22x22,
   * the full array per the datasheet's pixel address map). Clamped to
   * the firmware's static frame buffer size
   * (CONFIG_ZMK_PMW3610_STUDIO_RPC_FRAME_BUF_SIZE).
   */
  pixelCount: number;
  /**
   * Max 10ms-wait retries per pixel while waiting for OBSERVATION1 bit2
   * (pixel-ready) before the capture aborts, returning whatever was
   * collected so far. 0 means the driver default (3); clamped to 1..100.
   */
  maxInvalidRetries: number;
}

export interface CaptureFrameResponse {
  frameId: number;
  /**
   * Number of pixel bytes actually collected (<= requested pixel_count;
   * may be less if the capture aborted early on repeated not-ready
   * waits).
   */
  pixelCount: number;
  /**
   * Chunk size used by GetFrameChunk for this frame (fixed, currently
   * 128; see pmw3610.options for the actual bound).
   */
  chunkSize: number;
  /**
   * PRBS_TEST_CTL (0x47) bit0 as read after the pixel loop: set when the
   * sensor reports all 484 pixels were read successfully.
   */
  complete: boolean;
  /**
   * Wall-clock duration of the capture procedure (arm sequence through
   * the completion check), in milliseconds.
   */
  durationMs: number;
}

/** Fetch a chunk of a previously captured frame's pixel bytes. */
export interface GetFrameChunkRequest {
  frameId: number;
  offset: number;
}

export interface GetFrameChunkResponse {
  frameId: number;
  offset: number;
  /**
   * Raw pixel bytes (bit7 = PG_VALID, bits[6:0] = pixel value). The host
   * is responsible for masking/scaling; invalid (bit7==0) bytes are kept
   * as-is so the host can detect/report capture quality.
   */
  data: Uint8Array;
}

/**
 * Starts/stops a background capture loop that raises one `FrameStreamChunk`
 * Notification per 128-byte chunk of every captured frame (see
 * `Notification` below), instead of the client having to poll
 * CaptureFrame+GetFrameChunk in a loop. Shares the same static frame
 * buffer/frame_id counter as CaptureFrame/GetFrameChunk, so only one of
 * "streaming" or a one-shot CaptureFrame can be active at a time --
 * CaptureFrame rejects with an ErrorResponse while streaming is enabled.
 */
export interface SetFrameStreamRequest {
  deviceIndex: number;
  enable: boolean;
  /** 0 = driver default, same as CaptureFrameRequest. */
  pixelCount: number;
  /** 0 = driver default, same as CaptureFrameRequest. */
  maxInvalidRetries: number;
}

export interface SetFrameStreamResponse {
  /** Streaming state after applying this request. */
  streaming: boolean;
}

export interface Request {
  getInfo?: GetInfoRequest | undefined;
  readDiagnostics?: ReadDiagnosticsRequest | undefined;
  readRegister?: ReadRegisterRequest | undefined;
  writeRegister?: WriteRegisterRequest | undefined;
  captureFrame?: CaptureFrameRequest | undefined;
  getFrameChunk?: GetFrameChunkRequest | undefined;
  setFrameStream?: SetFrameStreamRequest | undefined;
}

export interface ErrorResponse {
  message: string;
}

export interface Response {
  error?: ErrorResponse | undefined;
  getInfo?: GetInfoResponse | undefined;
  readDiagnostics?: ReadDiagnosticsResponse | undefined;
  readRegister?: ReadRegisterResponse | undefined;
  writeRegister?: WriteRegisterResponse | undefined;
  captureFrame?: CaptureFrameResponse | undefined;
  getFrameChunk?: GetFrameChunkResponse | undefined;
  setFrameStream?: SetFrameStreamResponse | undefined;
}

/**
 * One 128-byte-or-less chunk of a frame captured while streaming
 * (SetFrameStream{enable: true}) is active. Raised as a custom Studio
 * notification (not a Request/Response) via the `cormoran__pmw3610`
 * subsystem, mirroring zmk-feature-custom-settings' own Notification
 * pattern.
 */
export interface FrameStreamChunk {
  frameId: number;
  offset: number;
  /**
   * <=128 bytes, same bound as GetFrameChunkResponse.data (see
   * pmw3610.options).
   */
  data: Uint8Array;
  /**
   * Total frame length in bytes; repeated on every chunk of the same
   * frame so the client can detect the last chunk without a separate
   * "done" message.
   */
  totalSize: number;
  /**
   * PRBS_TEST_CTL (0x47) bit0 as read after this frame's capture (same
   * meaning as CaptureFrameResponse.complete); repeated on every chunk of
   * the same frame.
   */
  complete: boolean;
}

export interface Notification {
  frameStreamChunk?: FrameStreamChunk | undefined;
}

function createBaseGetInfoRequest(): GetInfoRequest {
  return {};
}

export const GetInfoRequest: MessageFns<GetInfoRequest> = {
  encode(_: GetInfoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetInfoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetInfoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetInfoRequest>): GetInfoRequest {
    return GetInfoRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<GetInfoRequest>): GetInfoRequest {
    const message = createBaseGetInfoRequest();
    return message;
  },
};

function createBaseRuntimeConfig(): RuntimeConfig {
  return {
    cpi: 0,
    swapXy: false,
    invertX: false,
    invertY: false,
    forceAwake: false,
    smartAlgorithm: false,
    runDownshiftMs: 0,
    rest1DownshiftMs: 0,
    rest2DownshiftMs: 0,
    rest1SampleMs: 0,
    rest2SampleMs: 0,
    rest3SampleMs: 0,
    reportIntervalMinMs: 0,
  };
}

export const RuntimeConfig: MessageFns<RuntimeConfig> = {
  encode(message: RuntimeConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cpi !== 0) {
      writer.uint32(8).uint32(message.cpi);
    }
    if (message.swapXy !== false) {
      writer.uint32(16).bool(message.swapXy);
    }
    if (message.invertX !== false) {
      writer.uint32(24).bool(message.invertX);
    }
    if (message.invertY !== false) {
      writer.uint32(32).bool(message.invertY);
    }
    if (message.forceAwake !== false) {
      writer.uint32(40).bool(message.forceAwake);
    }
    if (message.smartAlgorithm !== false) {
      writer.uint32(48).bool(message.smartAlgorithm);
    }
    if (message.runDownshiftMs !== 0) {
      writer.uint32(56).uint32(message.runDownshiftMs);
    }
    if (message.rest1DownshiftMs !== 0) {
      writer.uint32(64).uint32(message.rest1DownshiftMs);
    }
    if (message.rest2DownshiftMs !== 0) {
      writer.uint32(72).uint32(message.rest2DownshiftMs);
    }
    if (message.rest1SampleMs !== 0) {
      writer.uint32(80).uint32(message.rest1SampleMs);
    }
    if (message.rest2SampleMs !== 0) {
      writer.uint32(88).uint32(message.rest2SampleMs);
    }
    if (message.rest3SampleMs !== 0) {
      writer.uint32(96).uint32(message.rest3SampleMs);
    }
    if (message.reportIntervalMinMs !== 0) {
      writer.uint32(104).uint32(message.reportIntervalMinMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RuntimeConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRuntimeConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.cpi = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.swapXy = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.invertX = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.invertY = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.forceAwake = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.smartAlgorithm = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.runDownshiftMs = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.rest1DownshiftMs = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.rest2DownshiftMs = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.rest1SampleMs = reader.uint32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.rest2SampleMs = reader.uint32();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.rest3SampleMs = reader.uint32();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.reportIntervalMinMs = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<RuntimeConfig>): RuntimeConfig {
    return RuntimeConfig.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RuntimeConfig>): RuntimeConfig {
    const message = createBaseRuntimeConfig();
    message.cpi = object.cpi ?? 0;
    message.swapXy = object.swapXy ?? false;
    message.invertX = object.invertX ?? false;
    message.invertY = object.invertY ?? false;
    message.forceAwake = object.forceAwake ?? false;
    message.smartAlgorithm = object.smartAlgorithm ?? false;
    message.runDownshiftMs = object.runDownshiftMs ?? 0;
    message.rest1DownshiftMs = object.rest1DownshiftMs ?? 0;
    message.rest2DownshiftMs = object.rest2DownshiftMs ?? 0;
    message.rest1SampleMs = object.rest1SampleMs ?? 0;
    message.rest2SampleMs = object.rest2SampleMs ?? 0;
    message.rest3SampleMs = object.rest3SampleMs ?? 0;
    message.reportIntervalMinMs = object.reportIntervalMinMs ?? 0;
    return message;
  },
};

function createBaseDeviceInfo(): DeviceInfo {
  return { ready: false, productId: 0, revisionId: 0, initError: 0, runtimeConfig: undefined };
}

export const DeviceInfo: MessageFns<DeviceInfo> = {
  encode(message: DeviceInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ready !== false) {
      writer.uint32(8).bool(message.ready);
    }
    if (message.productId !== 0) {
      writer.uint32(16).uint32(message.productId);
    }
    if (message.revisionId !== 0) {
      writer.uint32(24).uint32(message.revisionId);
    }
    if (message.initError !== 0) {
      writer.uint32(32).int32(message.initError);
    }
    if (message.runtimeConfig !== undefined) {
      RuntimeConfig.encode(message.runtimeConfig, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeviceInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeviceInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ready = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.productId = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.revisionId = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.initError = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.runtimeConfig = RuntimeConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<DeviceInfo>): DeviceInfo {
    return DeviceInfo.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeviceInfo>): DeviceInfo {
    const message = createBaseDeviceInfo();
    message.ready = object.ready ?? false;
    message.productId = object.productId ?? 0;
    message.revisionId = object.revisionId ?? 0;
    message.initError = object.initError ?? 0;
    message.runtimeConfig = (object.runtimeConfig !== undefined && object.runtimeConfig !== null)
      ? RuntimeConfig.fromPartial(object.runtimeConfig)
      : undefined;
    return message;
  },
};

function createBaseGetInfoResponse(): GetInfoResponse {
  return { devices: [] };
}

export const GetInfoResponse: MessageFns<GetInfoResponse> = {
  encode(message: GetInfoResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.devices) {
      DeviceInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetInfoResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetInfoResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.devices.push(DeviceInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetInfoResponse>): GetInfoResponse {
    return GetInfoResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetInfoResponse>): GetInfoResponse {
    const message = createBaseGetInfoResponse();
    message.devices = object.devices?.map((e) => DeviceInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseReadDiagnosticsRequest(): ReadDiagnosticsRequest {
  return { deviceIndex: 0 };
}

export const ReadDiagnosticsRequest: MessageFns<ReadDiagnosticsRequest> = {
  encode(message: ReadDiagnosticsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deviceIndex !== 0) {
      writer.uint32(8).uint32(message.deviceIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadDiagnosticsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadDiagnosticsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.deviceIndex = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ReadDiagnosticsRequest>): ReadDiagnosticsRequest {
    return ReadDiagnosticsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ReadDiagnosticsRequest>): ReadDiagnosticsRequest {
    const message = createBaseReadDiagnosticsRequest();
    message.deviceIndex = object.deviceIndex ?? 0;
    return message;
  },
};

function createBaseReadDiagnosticsResponse(): ReadDiagnosticsResponse {
  return { squal: 0, shutter: 0, pixMax: 0, pixAvg: 0, pixMin: 0 };
}

export const ReadDiagnosticsResponse: MessageFns<ReadDiagnosticsResponse> = {
  encode(message: ReadDiagnosticsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.squal !== 0) {
      writer.uint32(8).uint32(message.squal);
    }
    if (message.shutter !== 0) {
      writer.uint32(16).uint32(message.shutter);
    }
    if (message.pixMax !== 0) {
      writer.uint32(24).uint32(message.pixMax);
    }
    if (message.pixAvg !== 0) {
      writer.uint32(32).uint32(message.pixAvg);
    }
    if (message.pixMin !== 0) {
      writer.uint32(40).uint32(message.pixMin);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadDiagnosticsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadDiagnosticsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.squal = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.shutter = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.pixMax = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.pixAvg = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.pixMin = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ReadDiagnosticsResponse>): ReadDiagnosticsResponse {
    return ReadDiagnosticsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ReadDiagnosticsResponse>): ReadDiagnosticsResponse {
    const message = createBaseReadDiagnosticsResponse();
    message.squal = object.squal ?? 0;
    message.shutter = object.shutter ?? 0;
    message.pixMax = object.pixMax ?? 0;
    message.pixAvg = object.pixAvg ?? 0;
    message.pixMin = object.pixMin ?? 0;
    return message;
  },
};

function createBaseReadRegisterRequest(): ReadRegisterRequest {
  return { deviceIndex: 0, address: 0 };
}

export const ReadRegisterRequest: MessageFns<ReadRegisterRequest> = {
  encode(message: ReadRegisterRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deviceIndex !== 0) {
      writer.uint32(8).uint32(message.deviceIndex);
    }
    if (message.address !== 0) {
      writer.uint32(16).uint32(message.address);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadRegisterRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadRegisterRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.deviceIndex = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.address = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ReadRegisterRequest>): ReadRegisterRequest {
    return ReadRegisterRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ReadRegisterRequest>): ReadRegisterRequest {
    const message = createBaseReadRegisterRequest();
    message.deviceIndex = object.deviceIndex ?? 0;
    message.address = object.address ?? 0;
    return message;
  },
};

function createBaseReadRegisterResponse(): ReadRegisterResponse {
  return { value: 0 };
}

export const ReadRegisterResponse: MessageFns<ReadRegisterResponse> = {
  encode(message: ReadRegisterResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== 0) {
      writer.uint32(8).uint32(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadRegisterResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadRegisterResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.value = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ReadRegisterResponse>): ReadRegisterResponse {
    return ReadRegisterResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ReadRegisterResponse>): ReadRegisterResponse {
    const message = createBaseReadRegisterResponse();
    message.value = object.value ?? 0;
    return message;
  },
};

function createBaseWriteRegisterRequest(): WriteRegisterRequest {
  return { deviceIndex: 0, address: 0, value: 0 };
}

export const WriteRegisterRequest: MessageFns<WriteRegisterRequest> = {
  encode(message: WriteRegisterRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deviceIndex !== 0) {
      writer.uint32(8).uint32(message.deviceIndex);
    }
    if (message.address !== 0) {
      writer.uint32(16).uint32(message.address);
    }
    if (message.value !== 0) {
      writer.uint32(24).uint32(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WriteRegisterRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWriteRegisterRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.deviceIndex = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.address = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.value = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<WriteRegisterRequest>): WriteRegisterRequest {
    return WriteRegisterRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<WriteRegisterRequest>): WriteRegisterRequest {
    const message = createBaseWriteRegisterRequest();
    message.deviceIndex = object.deviceIndex ?? 0;
    message.address = object.address ?? 0;
    message.value = object.value ?? 0;
    return message;
  },
};

function createBaseWriteRegisterResponse(): WriteRegisterResponse {
  return {};
}

export const WriteRegisterResponse: MessageFns<WriteRegisterResponse> = {
  encode(_: WriteRegisterResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WriteRegisterResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWriteRegisterResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<WriteRegisterResponse>): WriteRegisterResponse {
    return WriteRegisterResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<WriteRegisterResponse>): WriteRegisterResponse {
    const message = createBaseWriteRegisterResponse();
    return message;
  },
};

function createBaseCaptureFrameRequest(): CaptureFrameRequest {
  return { deviceIndex: 0, pixelCount: 0, maxInvalidRetries: 0 };
}

export const CaptureFrameRequest: MessageFns<CaptureFrameRequest> = {
  encode(message: CaptureFrameRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deviceIndex !== 0) {
      writer.uint32(8).uint32(message.deviceIndex);
    }
    if (message.pixelCount !== 0) {
      writer.uint32(16).uint32(message.pixelCount);
    }
    if (message.maxInvalidRetries !== 0) {
      writer.uint32(24).uint32(message.maxInvalidRetries);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CaptureFrameRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCaptureFrameRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.deviceIndex = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pixelCount = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.maxInvalidRetries = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CaptureFrameRequest>): CaptureFrameRequest {
    return CaptureFrameRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CaptureFrameRequest>): CaptureFrameRequest {
    const message = createBaseCaptureFrameRequest();
    message.deviceIndex = object.deviceIndex ?? 0;
    message.pixelCount = object.pixelCount ?? 0;
    message.maxInvalidRetries = object.maxInvalidRetries ?? 0;
    return message;
  },
};

function createBaseCaptureFrameResponse(): CaptureFrameResponse {
  return { frameId: 0, pixelCount: 0, chunkSize: 0, complete: false, durationMs: 0 };
}

export const CaptureFrameResponse: MessageFns<CaptureFrameResponse> = {
  encode(message: CaptureFrameResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.frameId !== 0) {
      writer.uint32(8).uint32(message.frameId);
    }
    if (message.pixelCount !== 0) {
      writer.uint32(16).uint32(message.pixelCount);
    }
    if (message.chunkSize !== 0) {
      writer.uint32(24).uint32(message.chunkSize);
    }
    if (message.complete !== false) {
      writer.uint32(32).bool(message.complete);
    }
    if (message.durationMs !== 0) {
      writer.uint32(40).uint32(message.durationMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CaptureFrameResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCaptureFrameResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.frameId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pixelCount = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.chunkSize = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.complete = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.durationMs = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CaptureFrameResponse>): CaptureFrameResponse {
    return CaptureFrameResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CaptureFrameResponse>): CaptureFrameResponse {
    const message = createBaseCaptureFrameResponse();
    message.frameId = object.frameId ?? 0;
    message.pixelCount = object.pixelCount ?? 0;
    message.chunkSize = object.chunkSize ?? 0;
    message.complete = object.complete ?? false;
    message.durationMs = object.durationMs ?? 0;
    return message;
  },
};

function createBaseGetFrameChunkRequest(): GetFrameChunkRequest {
  return { frameId: 0, offset: 0 };
}

export const GetFrameChunkRequest: MessageFns<GetFrameChunkRequest> = {
  encode(message: GetFrameChunkRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.frameId !== 0) {
      writer.uint32(8).uint32(message.frameId);
    }
    if (message.offset !== 0) {
      writer.uint32(16).uint32(message.offset);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetFrameChunkRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetFrameChunkRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.frameId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.offset = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetFrameChunkRequest>): GetFrameChunkRequest {
    return GetFrameChunkRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetFrameChunkRequest>): GetFrameChunkRequest {
    const message = createBaseGetFrameChunkRequest();
    message.frameId = object.frameId ?? 0;
    message.offset = object.offset ?? 0;
    return message;
  },
};

function createBaseGetFrameChunkResponse(): GetFrameChunkResponse {
  return { frameId: 0, offset: 0, data: new Uint8Array(0) };
}

export const GetFrameChunkResponse: MessageFns<GetFrameChunkResponse> = {
  encode(message: GetFrameChunkResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.frameId !== 0) {
      writer.uint32(8).uint32(message.frameId);
    }
    if (message.offset !== 0) {
      writer.uint32(16).uint32(message.offset);
    }
    if (message.data.length !== 0) {
      writer.uint32(26).bytes(message.data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetFrameChunkResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetFrameChunkResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.frameId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.offset = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetFrameChunkResponse>): GetFrameChunkResponse {
    return GetFrameChunkResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetFrameChunkResponse>): GetFrameChunkResponse {
    const message = createBaseGetFrameChunkResponse();
    message.frameId = object.frameId ?? 0;
    message.offset = object.offset ?? 0;
    message.data = object.data ?? new Uint8Array(0);
    return message;
  },
};

function createBaseSetFrameStreamRequest(): SetFrameStreamRequest {
  return { deviceIndex: 0, enable: false, pixelCount: 0, maxInvalidRetries: 0 };
}

export const SetFrameStreamRequest: MessageFns<SetFrameStreamRequest> = {
  encode(message: SetFrameStreamRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deviceIndex !== 0) {
      writer.uint32(8).uint32(message.deviceIndex);
    }
    if (message.enable !== false) {
      writer.uint32(16).bool(message.enable);
    }
    if (message.pixelCount !== 0) {
      writer.uint32(24).uint32(message.pixelCount);
    }
    if (message.maxInvalidRetries !== 0) {
      writer.uint32(32).uint32(message.maxInvalidRetries);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetFrameStreamRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetFrameStreamRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.deviceIndex = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.enable = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.pixelCount = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.maxInvalidRetries = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetFrameStreamRequest>): SetFrameStreamRequest {
    return SetFrameStreamRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetFrameStreamRequest>): SetFrameStreamRequest {
    const message = createBaseSetFrameStreamRequest();
    message.deviceIndex = object.deviceIndex ?? 0;
    message.enable = object.enable ?? false;
    message.pixelCount = object.pixelCount ?? 0;
    message.maxInvalidRetries = object.maxInvalidRetries ?? 0;
    return message;
  },
};

function createBaseSetFrameStreamResponse(): SetFrameStreamResponse {
  return { streaming: false };
}

export const SetFrameStreamResponse: MessageFns<SetFrameStreamResponse> = {
  encode(message: SetFrameStreamResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.streaming !== false) {
      writer.uint32(8).bool(message.streaming);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetFrameStreamResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetFrameStreamResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.streaming = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetFrameStreamResponse>): SetFrameStreamResponse {
    return SetFrameStreamResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetFrameStreamResponse>): SetFrameStreamResponse {
    const message = createBaseSetFrameStreamResponse();
    message.streaming = object.streaming ?? false;
    return message;
  },
};

function createBaseRequest(): Request {
  return {
    getInfo: undefined,
    readDiagnostics: undefined,
    readRegister: undefined,
    writeRegister: undefined,
    captureFrame: undefined,
    getFrameChunk: undefined,
    setFrameStream: undefined,
  };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.getInfo !== undefined) {
      GetInfoRequest.encode(message.getInfo, writer.uint32(10).fork()).join();
    }
    if (message.readDiagnostics !== undefined) {
      ReadDiagnosticsRequest.encode(message.readDiagnostics, writer.uint32(18).fork()).join();
    }
    if (message.readRegister !== undefined) {
      ReadRegisterRequest.encode(message.readRegister, writer.uint32(26).fork()).join();
    }
    if (message.writeRegister !== undefined) {
      WriteRegisterRequest.encode(message.writeRegister, writer.uint32(34).fork()).join();
    }
    if (message.captureFrame !== undefined) {
      CaptureFrameRequest.encode(message.captureFrame, writer.uint32(42).fork()).join();
    }
    if (message.getFrameChunk !== undefined) {
      GetFrameChunkRequest.encode(message.getFrameChunk, writer.uint32(50).fork()).join();
    }
    if (message.setFrameStream !== undefined) {
      SetFrameStreamRequest.encode(message.setFrameStream, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.getInfo = GetInfoRequest.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.readDiagnostics = ReadDiagnosticsRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.readRegister = ReadRegisterRequest.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.writeRegister = WriteRegisterRequest.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.captureFrame = CaptureFrameRequest.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.getFrameChunk = GetFrameChunkRequest.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.setFrameStream = SetFrameStreamRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Request>): Request {
    return Request.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Request>): Request {
    const message = createBaseRequest();
    message.getInfo = (object.getInfo !== undefined && object.getInfo !== null)
      ? GetInfoRequest.fromPartial(object.getInfo)
      : undefined;
    message.readDiagnostics = (object.readDiagnostics !== undefined && object.readDiagnostics !== null)
      ? ReadDiagnosticsRequest.fromPartial(object.readDiagnostics)
      : undefined;
    message.readRegister = (object.readRegister !== undefined && object.readRegister !== null)
      ? ReadRegisterRequest.fromPartial(object.readRegister)
      : undefined;
    message.writeRegister = (object.writeRegister !== undefined && object.writeRegister !== null)
      ? WriteRegisterRequest.fromPartial(object.writeRegister)
      : undefined;
    message.captureFrame = (object.captureFrame !== undefined && object.captureFrame !== null)
      ? CaptureFrameRequest.fromPartial(object.captureFrame)
      : undefined;
    message.getFrameChunk = (object.getFrameChunk !== undefined && object.getFrameChunk !== null)
      ? GetFrameChunkRequest.fromPartial(object.getFrameChunk)
      : undefined;
    message.setFrameStream = (object.setFrameStream !== undefined && object.setFrameStream !== null)
      ? SetFrameStreamRequest.fromPartial(object.setFrameStream)
      : undefined;
    return message;
  },
};

function createBaseErrorResponse(): ErrorResponse {
  return { message: "" };
}

export const ErrorResponse: MessageFns<ErrorResponse> = {
  encode(message: ErrorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ErrorResponse>): ErrorResponse {
    return ErrorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ErrorResponse>): ErrorResponse {
    const message = createBaseErrorResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseResponse(): Response {
  return {
    error: undefined,
    getInfo: undefined,
    readDiagnostics: undefined,
    readRegister: undefined,
    writeRegister: undefined,
    captureFrame: undefined,
    getFrameChunk: undefined,
    setFrameStream: undefined,
  };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(10).fork()).join();
    }
    if (message.getInfo !== undefined) {
      GetInfoResponse.encode(message.getInfo, writer.uint32(18).fork()).join();
    }
    if (message.readDiagnostics !== undefined) {
      ReadDiagnosticsResponse.encode(message.readDiagnostics, writer.uint32(26).fork()).join();
    }
    if (message.readRegister !== undefined) {
      ReadRegisterResponse.encode(message.readRegister, writer.uint32(34).fork()).join();
    }
    if (message.writeRegister !== undefined) {
      WriteRegisterResponse.encode(message.writeRegister, writer.uint32(42).fork()).join();
    }
    if (message.captureFrame !== undefined) {
      CaptureFrameResponse.encode(message.captureFrame, writer.uint32(50).fork()).join();
    }
    if (message.getFrameChunk !== undefined) {
      GetFrameChunkResponse.encode(message.getFrameChunk, writer.uint32(58).fork()).join();
    }
    if (message.setFrameStream !== undefined) {
      SetFrameStreamResponse.encode(message.setFrameStream, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.getInfo = GetInfoResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.readDiagnostics = ReadDiagnosticsResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.readRegister = ReadRegisterResponse.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.writeRegister = WriteRegisterResponse.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.captureFrame = CaptureFrameResponse.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.getFrameChunk = GetFrameChunkResponse.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.setFrameStream = SetFrameStreamResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Response>): Response {
    return Response.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Response>): Response {
    const message = createBaseResponse();
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    message.getInfo = (object.getInfo !== undefined && object.getInfo !== null)
      ? GetInfoResponse.fromPartial(object.getInfo)
      : undefined;
    message.readDiagnostics = (object.readDiagnostics !== undefined && object.readDiagnostics !== null)
      ? ReadDiagnosticsResponse.fromPartial(object.readDiagnostics)
      : undefined;
    message.readRegister = (object.readRegister !== undefined && object.readRegister !== null)
      ? ReadRegisterResponse.fromPartial(object.readRegister)
      : undefined;
    message.writeRegister = (object.writeRegister !== undefined && object.writeRegister !== null)
      ? WriteRegisterResponse.fromPartial(object.writeRegister)
      : undefined;
    message.captureFrame = (object.captureFrame !== undefined && object.captureFrame !== null)
      ? CaptureFrameResponse.fromPartial(object.captureFrame)
      : undefined;
    message.getFrameChunk = (object.getFrameChunk !== undefined && object.getFrameChunk !== null)
      ? GetFrameChunkResponse.fromPartial(object.getFrameChunk)
      : undefined;
    message.setFrameStream = (object.setFrameStream !== undefined && object.setFrameStream !== null)
      ? SetFrameStreamResponse.fromPartial(object.setFrameStream)
      : undefined;
    return message;
  },
};

function createBaseFrameStreamChunk(): FrameStreamChunk {
  return { frameId: 0, offset: 0, data: new Uint8Array(0), totalSize: 0, complete: false };
}

export const FrameStreamChunk: MessageFns<FrameStreamChunk> = {
  encode(message: FrameStreamChunk, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.frameId !== 0) {
      writer.uint32(8).uint32(message.frameId);
    }
    if (message.offset !== 0) {
      writer.uint32(16).uint32(message.offset);
    }
    if (message.data.length !== 0) {
      writer.uint32(26).bytes(message.data);
    }
    if (message.totalSize !== 0) {
      writer.uint32(32).uint32(message.totalSize);
    }
    if (message.complete !== false) {
      writer.uint32(40).bool(message.complete);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FrameStreamChunk {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFrameStreamChunk();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.frameId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.offset = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.totalSize = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.complete = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FrameStreamChunk>): FrameStreamChunk {
    return FrameStreamChunk.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FrameStreamChunk>): FrameStreamChunk {
    const message = createBaseFrameStreamChunk();
    message.frameId = object.frameId ?? 0;
    message.offset = object.offset ?? 0;
    message.data = object.data ?? new Uint8Array(0);
    message.totalSize = object.totalSize ?? 0;
    message.complete = object.complete ?? false;
    return message;
  },
};

function createBaseNotification(): Notification {
  return { frameStreamChunk: undefined };
}

export const Notification: MessageFns<Notification> = {
  encode(message: Notification, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.frameStreamChunk !== undefined) {
      FrameStreamChunk.encode(message.frameStreamChunk, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Notification {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.frameStreamChunk = FrameStreamChunk.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Notification>): Notification {
    return Notification.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Notification>): Notification {
    const message = createBaseNotification();
    message.frameStreamChunk = (object.frameStreamChunk !== undefined && object.frameStreamChunk !== null)
      ? FrameStreamChunk.fromPartial(object.frameStreamChunk)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
