// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: zmk/input_stream/input_stream.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "zmk.input_stream";

export interface EnableStreamRequest {
}

export interface DisableStreamRequest {
}

export interface Request {
  enableStream?: EnableStreamRequest | undefined;
  disableStream?: DisableStreamRequest | undefined;
}

export interface ErrorResponse {
  message: string;
}

export interface OkResponse {
}

export interface Response {
  error?: ErrorResponse | undefined;
  ok?: OkResponse | undefined;
}

/**
 * Sent when a key is physically pressed or released.
 * behavior_id/param1/param2 come from the active-layer binding at that position.
 */
export interface KeyEventNotification {
  position: number;
  pressed: boolean;
  behaviorId: number;
  param1: number;
  param2: number;
}

/** Sent whenever the highest-active-layer index changes. */
export interface LayerChangeNotification {
  layerIndex: number;
}

export interface Notification {
  keyEvent?: KeyEventNotification | undefined;
  layerChange?: LayerChangeNotification | undefined;
}

function createBaseEnableStreamRequest(): EnableStreamRequest {
  return {};
}

export const EnableStreamRequest: MessageFns<EnableStreamRequest> = {
  encode(_: EnableStreamRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EnableStreamRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEnableStreamRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<EnableStreamRequest>): EnableStreamRequest {
    return EnableStreamRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<EnableStreamRequest>): EnableStreamRequest {
    const message = createBaseEnableStreamRequest();
    return message;
  },
};

function createBaseDisableStreamRequest(): DisableStreamRequest {
  return {};
}

export const DisableStreamRequest: MessageFns<DisableStreamRequest> = {
  encode(_: DisableStreamRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DisableStreamRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDisableStreamRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<DisableStreamRequest>): DisableStreamRequest {
    return DisableStreamRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<DisableStreamRequest>): DisableStreamRequest {
    const message = createBaseDisableStreamRequest();
    return message;
  },
};

function createBaseRequest(): Request {
  return { enableStream: undefined, disableStream: undefined };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.enableStream !== undefined) {
      EnableStreamRequest.encode(message.enableStream, writer.uint32(10).fork()).join();
    }
    if (message.disableStream !== undefined) {
      DisableStreamRequest.encode(message.disableStream, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.enableStream = EnableStreamRequest.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.disableStream = DisableStreamRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Request>): Request {
    return Request.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Request>): Request {
    const message = createBaseRequest();
    message.enableStream = (object.enableStream !== undefined && object.enableStream !== null)
      ? EnableStreamRequest.fromPartial(object.enableStream)
      : undefined;
    message.disableStream = (object.disableStream !== undefined && object.disableStream !== null)
      ? DisableStreamRequest.fromPartial(object.disableStream)
      : undefined;
    return message;
  },
};

function createBaseErrorResponse(): ErrorResponse {
  return { message: "" };
}

export const ErrorResponse: MessageFns<ErrorResponse> = {
  encode(message: ErrorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ErrorResponse>): ErrorResponse {
    return ErrorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ErrorResponse>): ErrorResponse {
    const message = createBaseErrorResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseOkResponse(): OkResponse {
  return {};
}

export const OkResponse: MessageFns<OkResponse> = {
  encode(_: OkResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OkResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOkResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<OkResponse>): OkResponse {
    return OkResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<OkResponse>): OkResponse {
    const message = createBaseOkResponse();
    return message;
  },
};

function createBaseResponse(): Response {
  return { error: undefined, ok: undefined };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(10).fork()).join();
    }
    if (message.ok !== undefined) {
      OkResponse.encode(message.ok, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ok = OkResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Response>): Response {
    return Response.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Response>): Response {
    const message = createBaseResponse();
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    message.ok = (object.ok !== undefined && object.ok !== null) ? OkResponse.fromPartial(object.ok) : undefined;
    return message;
  },
};

function createBaseKeyEventNotification(): KeyEventNotification {
  return { position: 0, pressed: false, behaviorId: 0, param1: 0, param2: 0 };
}

export const KeyEventNotification: MessageFns<KeyEventNotification> = {
  encode(message: KeyEventNotification, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.position !== 0) {
      writer.uint32(8).uint32(message.position);
    }
    if (message.pressed !== false) {
      writer.uint32(16).bool(message.pressed);
    }
    if (message.behaviorId !== 0) {
      writer.uint32(24).uint32(message.behaviorId);
    }
    if (message.param1 !== 0) {
      writer.uint32(32).uint32(message.param1);
    }
    if (message.param2 !== 0) {
      writer.uint32(40).uint32(message.param2);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): KeyEventNotification {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeyEventNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.position = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pressed = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.behaviorId = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.param1 = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.param2 = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<KeyEventNotification>): KeyEventNotification {
    return KeyEventNotification.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<KeyEventNotification>): KeyEventNotification {
    const message = createBaseKeyEventNotification();
    message.position = object.position ?? 0;
    message.pressed = object.pressed ?? false;
    message.behaviorId = object.behaviorId ?? 0;
    message.param1 = object.param1 ?? 0;
    message.param2 = object.param2 ?? 0;
    return message;
  },
};

function createBaseLayerChangeNotification(): LayerChangeNotification {
  return { layerIndex: 0 };
}

export const LayerChangeNotification: MessageFns<LayerChangeNotification> = {
  encode(message: LayerChangeNotification, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.layerIndex !== 0) {
      writer.uint32(8).uint32(message.layerIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LayerChangeNotification {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLayerChangeNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.layerIndex = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<LayerChangeNotification>): LayerChangeNotification {
    return LayerChangeNotification.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<LayerChangeNotification>): LayerChangeNotification {
    const message = createBaseLayerChangeNotification();
    message.layerIndex = object.layerIndex ?? 0;
    return message;
  },
};

function createBaseNotification(): Notification {
  return { keyEvent: undefined, layerChange: undefined };
}

export const Notification: MessageFns<Notification> = {
  encode(message: Notification, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.keyEvent !== undefined) {
      KeyEventNotification.encode(message.keyEvent, writer.uint32(10).fork()).join();
    }
    if (message.layerChange !== undefined) {
      LayerChangeNotification.encode(message.layerChange, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Notification {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.keyEvent = KeyEventNotification.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.layerChange = LayerChangeNotification.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Notification>): Notification {
    return Notification.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Notification>): Notification {
    const message = createBaseNotification();
    message.keyEvent = (object.keyEvent !== undefined && object.keyEvent !== null)
      ? KeyEventNotification.fromPartial(object.keyEvent)
      : undefined;
    message.layerChange = (object.layerChange !== undefined && object.layerChange !== null)
      ? LayerChangeNotification.fromPartial(object.layerChange)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
