name: Release DYA Studio

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: cloudflare-release
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          VITE_BASE: /
          VITE_GOOGLE_ANALYTICS_ID: ${{ secrets.VITE_GOOGLE_ANALYTICS_ID }}
      - name: Deploy to Cloudflare Pages
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_RELEASE }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_RELEASE }}
          environment: release
          wranglerVersion: "4.58.0"
